<?xml version="1.0" encoding="UTF-8"?>
<saturn-action>
	<information id="0" next="" x="0" y="0">
		<key>/careModule/action/DeleteCare.action</key>
		<name>删除养护品信息</name>
		<description></description>
	</information>
	<action id="3" next="" x="497" y="166">
		<key>crm::/careModule/action/QueryCareList.action</key>
		<name>养护品信息列表</name>
		<parameters></parameters>
		<description></description>
	</action>
	<start id="1" next="2" x="81" y="161">
		<name>开始</name>
		<transaction autorollback="false"></transaction>
		<parameters></parameters>
		<description></description>
	</start>
	<logic exception="" id="2" next="3" x="283" y="162">
		<key>crm::/careModule/logic/DeleteCare.logic</key>
		<name>删除养护品信息</name>
		<transaction type="supports"></transaction>
		<parameters>
			<parameter id="1" name="primarykeyValue" classType="java.lang.String" passingType="in">
				<value-key>careid</value-key>
				<scope>1</scope>
				<description>primarykey</description>
			</parameter>
		</parameters>
		<description></description>
	</logic>
	<connection source="1" target="2" style="1" name=""></connection>
	<connection source="2" target="3" style="1" name=""></connection>
</saturn-action>