<?xml version="1.0" encoding="UTF-8"?>
<saturn-action>
	<information id="0" next="" x="0" y="0">
		<key>/ticketModule/action/DeleteTicket.action</key>
		<name>删除代金</name>
		<description>删除代金</description>
	</information>
	<start id="1" next="2" x="81" y="161">
		<name>开始</name>
		<transaction autorollback="false"></transaction>
		<parameters></parameters>
		<description></description>
	</start>
	<action id="4" next="" x="391" y="260">
		<key>crm::/ticketModule/action/QueryTicketDetailList.action</key>
		<name>QueryTicketDetailList</name>
		<parameters></parameters>
		<description></description>
	</action>
	<logic exception="" id="2" next="4" x="257" y="176">
		<key>crm::/ticketModule/logic/DeleteTicket.logic</key>
		<name>删除代金</name>
		<transaction type="supports"></transaction>
		<parameters>
			<parameter id="1" name="primarykeyValue" classType="java.lang.String" passingType="in">
				<value-key>ticketid</value-key>
				<scope>1</scope>
				<description>primarykey</description>
			</parameter>
			<parameter id="2" name="result" classType="java.lang.Integer" passingType="out">
				<value-key>result</value-key>
				<scope>1</scope>
				<description>sql执行所修改的记录条数</description>
			</parameter>
		</parameters>
		<description>删除代金</description>
	</logic>
	<connection source="1" target="2" style="1" name=""></connection>
	<connection source="2" target="4" style="1" name=""></connection>
</saturn-action>