<?xml version="1.0" encoding="UTF-8"?>
<saturn-action>
	<information id="0" next="" x="0" y="0">
		<key>/carModule/action/QueryCarByVin.action</key>
		<name>QueryCarByVin</name>
		<description></description>
	</information>
	<connection source="2" target="3" style="1" name=""></connection>
	<start id="1" next="4" x="81" y="161">
		<name>开始</name>
		<transaction autorollback="false"></transaction>
		<parameters></parameters>
		<description></description>
	</start>
	<logic exception="" id="4" next="7" x="253" y="159">
		<key>crm::/carModule/logic/QueryCarByVin.logic</key>
		<name>QueryCarByVin</name>
		<transaction type="supports"></transaction>
		<parameters>
			<parameter id="1" name="" classType="java.lang.String" passingType="in">
				<value-key>carvin</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="2" name="saturnData" classType="edu.ccut.saturn.component.SaturnData" passingType="out">
				<value-key>carData</value-key>
				<scope>1</scope>
				<description></description>
			</parameter>
			<parameter id="3" name="saturnData" classType="edu.ccut.saturn.component.SaturnData" passingType="out">
				<value-key>cstmData</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
		</parameters>
		<description></description>
	</logic>
	<decision next="" id="7" x="341" y="238">
		<name>选择2</name>
		<if then="8" else="9">
			<expr>carData==null</expr>
		</if>
		<parameters></parameters>
		<description></description>
	</decision>
	<view id="8" next="" x="503" y="338">
		<name>addcar</name>
		<type>jsp</type>
		<location>/crm/carModule/web/addcar.jsp</location>
		<description></description>
	</view>
	<webContext id="9" next="6" x="439" y="195">
		<name>网页上下文2</name>
		<value-moves>
			<value-move id="1" key="carData" scope="1" newKey="carData" newScope="2" isDelete="false"></value-move>
		</value-moves>
		<description></description>
	</webContext>
	<view id="10" next="" x="585" y="64">
		<name>editcar1</name>
		<type>jsp</type>
		<location>/crm/carModule/web/editcar1.jsp</location>
		<description></description>
	</view>
	<logic exception="" id="6" next="10" x="437" y="99">
		<key>crm::/memberModule/logic/QueryMemberByVin.logic</key>
		<name>QueryMemberByVin</name>
		<transaction type="supports"></transaction>
		<parameters>
			<parameter id="1" name="" classType="java.lang.String" passingType="in">
				<value-key>carvin</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="2" name="saturnData" classType="edu.ccut.saturn.component.SaturnData" passingType="out">
				<value-key>membData</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="3" name="target" classType="java.lang.String" passingType="out">
				<value-key>memberid</value-key>
				<scope>1</scope>
				<description></description>
			</parameter>
		</parameters>
		<description></description>
	</logic>
	<view id="5" next="" x="595" y="181">
		<name>editcar</name>
		<type>jsp</type>
		<location>/crm/carModule/web/editcar.jsp</location>
		<description></description>
	</view>
	<connection source="1" target="4" style="1" name=""></connection>
	<connection source="4" target="7" style="1" name=""></connection>
	<connection source="6" target="10" style="1" name=""></connection>
	<connection source="7" target="8" style="1" name="未命名"></connection>
	<connection source="7" target="9" style="2" name="未命名"></connection>
	<connection source="9" target="6" style="1" name=""></connection>
</saturn-action>