<?xml version="1.0" encoding="UTF-8"?>
<saturn-action>
	<information id="0" next="" x="0" y="0">
		<key>/reportModule/action/Quantity.action</key>
		<name>台次</name>
		<description></description>
	</information>
	<start id="1" next="4" x="81" y="161">
		<name>开始</name>
		<transaction autorollback="false"></transaction>
		<parameters></parameters>
		<description></description>
	</start>
	<view id="3" next="" x="488" y="166">
		<name>Quantity</name>
		<type>jsp</type>
		<location>/crm/reportModule/web/Quantity.jsp</location>
		<description></description>
	</view>
	<logic exception="" id="4" next="3" x="259" y="163">
		<key>crm::/reportModule/logic/Quantity.logic</key>
		<name>查询</name>
		<transaction type="supports"></transaction>
		<parameters>
			<parameter id="1" name="min_servintime" classType="java.lang.String" passingType="in-out">
				<value-key>min_servintime</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="2" name="max_servintime" classType="java.lang.String" passingType="in-out">
				<value-key>max_servintime</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="3" name="resultin" classType="java.util.ArrayList" passingType="out">
				<value-key>resultin</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="4" name="result" classType="java.util.ArrayList" passingType="out">
				<value-key>resultout</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="5" name="result" classType="java.util.ArrayList" passingType="out">
				<value-key>result</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
		</parameters>
		<description></description>
	</logic>
	<connection source="1" target="4" style="1" name=""></connection>
	<connection source="4" target="3" style="1" name=""></connection>
</saturn-action>