<?xml version="1.0" encoding="UTF-8"?>
<saturn-action>
	<information id="0" next="" x="0" y="0">
		<key>/jiyouModule/action/AddJYJson.action</key>
		<name>AddJYJson</name>
		<description></description>
	</information>
	<start id="1" next="3" x="81" y="161">
		<name>开始</name>
		<transaction autorollback="false"></transaction>
		<parameters></parameters>
		<description></description>
	</start>
	<connection source="4" target="5" style="1" name=""></connection>
	<data id="3" next="6" x="264" y="165">
		<name>数据1</name>
		<data-scope>2</data-scope>
		<data-prefix></data-prefix>
		<data-key>saturnData</data-key>
		<xmlkey></xmlkey>
		<elementkey></elementkey>
		<data-type classType="edu.ccut.saturn.component.SaturnData" namespace="http://crm/coreModule/data" saturnDataType="crm_jy"></data-type>
		<parameters></parameters>
		<description></description>
	</data>
	<view id="5" next="" x="755" y="166">
		<name>视图1</name>
		<type>json</type>
		<location>'true'</location>
		<description></description>
	</view>
	<logic exception="" id="6" next="5" x="453" y="156">
		<key>crm::/jiyouModule/logic/UpdateJYByOrderId.logic</key>
		<name>UpdateJYByOrderId</name>
		<transaction type="supports"></transaction>
		<parameters>
			<parameter id="1" name="" classType="java.lang.String" passingType="in">
				<value-key>${CRM_USER.userid}</value-key>
				<scope>5</scope>
				<description></description>
			</parameter>
			<parameter id="2" name="" classType="java.lang.String" passingType="in">
				<value-key>${CRM_USER.username}</value-key>
				<scope>5</scope>
				<description></description>
			</parameter>
			<parameter id="3" name="" classType="java.lang.String" passingType="in">
				<value-key>servorderid</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="4" name="" classType="edu.ccut.saturn.component.SaturnData" passingType="in">
				<value-key>saturnData</value-key>
				<scope>1</scope>
				<description></description>
			</parameter>
		</parameters>
		<description></description>
	</logic>
	<connection source="1" target="3" style="1" name=""></connection>
	<connection source="3" target="6" style="1" name=""></connection>
	<connection source="6" target="5" style="1" name=""></connection>
</saturn-action>