<?xml version="1.0" encoding="UTF-8"?>
<saturn-action>
	<information id="0" next="" x="0" y="0">
		<key>/jiyouModule/action/AddJY.action</key>
		<name>AddJY</name>
		<description></description>
	</information>
	<start id="1" next="3" x="81" y="161">
		<name>开始</name>
		<transaction autorollback="false"></transaction>
		<parameters></parameters>
		<description></description>
	</start>
	<action id="4" next="" x="588" y="203">
		<key>crm::/jiyouModule/action/QueryJYList.action</key>
		<name>QueryJYList</name>
		<parameters></parameters>
		<description></description>
	</action>
	<data id="3" next="2" x="256" y="171">
		<name>数据1</name>
		<data-scope>2</data-scope>
		<data-prefix>jy</data-prefix>
		<data-key>saturnData</data-key>
		<xmlkey></xmlkey>
		<elementkey></elementkey>
		<data-type classType="edu.ccut.saturn.component.SaturnData" namespace="http://crm/coreModule/data" saturnDataType="crm_jy"></data-type>
		<parameters></parameters>
		<description></description>
	</data>
	<logic exception="" id="2" next="4" x="389" y="177">
		<key>crm::/jiyouModule/logic/AddJY.logic</key>
		<name>AddJY</name>
		<transaction type="supports"></transaction>
		<parameters>
			<parameter id="1" name="saturnData" classType="edu.ccut.saturn.component.SaturnData" passingType="in">
				<value-key>saturnData</value-key>
				<scope>1</scope>
				<description></description>
			</parameter>
			<parameter id="2" name="" classType="java.lang.String" passingType="in">
				<value-key>${CRM_USER.userid}</value-key>
				<scope>5</scope>
				<description></description>
			</parameter>
			<parameter id="3" name="" classType="java.lang.String" passingType="in">
				<value-key>${CRM_USER.username}</value-key>
				<scope>5</scope>
				<description></description>
			</parameter>
		</parameters>
		<description></description>
	</logic>
	<connection source="1" target="3" style="1" name=""></connection>
	<connection source="2" target="4" style="1" name=""></connection>
	<connection source="3" target="2" style="1" name=""></connection>
</saturn-action>