<?xml version="1.0" encoding="UTF-8"?>
<saturn-action>
	<information id="0" next="" x="0" y="0">
		<key>/ccioModule/action/BindingExcel.action</key>
		<name>导出绑定列表</name>
		<description></description>
	</information>
	<start id="1" next="3" x="81" y="161">
		<name>开始</name>
		<transaction autorollback="false"></transaction>
		<parameters></parameters>
		<description></description>
	</start>
	<view id="2" next="" x="384" y="179">
		<name>bindingexcel</name>
		<type>jsp</type>
		<location>/crm/ccioModule/web/bindingexcel.jsp</location>
		<description></description>
	</view>
	<logic exception="" id="3" next="2" x="254" y="157">
		<key>crm::/ccioModule/logic/BindingExcel.logic</key>
		<name>导出绑定列表</name>
		<transaction type="supports"></transaction>
		<parameters>
			<parameter id="1" name="result" classType="java.util.ArrayList" passingType="out">
				<value-key>result</value-key>
				<scope>2</scope>
				<description>返回SaturnData结果集</description>
			</parameter>
			<parameter id="2" name="" classType="java.lang.String" passingType="in">
				<value-key>card</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="3" name="" classType="java.lang.String" passingType="in">
				<value-key>vin</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
		</parameters>
		<description></description>
	</logic>
	<connection source="1" target="3" style="1" name=""></connection>
	<connection source="3" target="2" style="1" name=""></connection>
</saturn-action>