<?xml version="1.0" encoding="UTF-8"?>
<saturn-action>
	<information id="0" next="" x="0" y="0">
		<key>/ccioModule/action/GetQueueDect.action</key>
		<name>排队获得详细数据</name>
		<description></description>
	</information>
	<decision next="" id="3" x="332" y="77">
		<name>io_vin!=null</name>
		<if then="2" else="6">
			<expr>io_vin!=null</expr>
		</if>
		<parameters></parameters>
		<description></description>
	</decision>
	<view id="6" next="" x="513" y="184">
		<name>queuedect</name>
		<type>jsp</type>
		<location>/crm/ccioModule/web/queuedect.jsp</location>
		<description></description>
	</view>
	<start id="1" next="5" x="81" y="161">
		<name>开始</name>
		<transaction autorollback="false"></transaction>
		<parameters></parameters>
		<description></description>
	</start>
	<logic exception="" id="4" next="3" x="202" y="69">
		<key>crm::/pointModule/logic/GetVinByNo.logic</key>
		<name>根据车牌号或发动机号获得VIN</name>
		<transaction type="supports"></transaction>
		<parameters>
			<parameter id="1" name="vin" classType="java.lang.String" passingType="out">
				<value-key>io_vin</value-key>
				<scope>1</scope>
				<description></description>
			</parameter>
			<parameter id="2" name="carlicenceno" classType="java.lang.String" passingType="in">
				<value-key>carlicenceno</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="3" name="carengineno" classType="java.lang.String" passingType="in">
				<value-key>carengineno</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
		</parameters>
		<description></description>
	</logic>
	<decision next="" id="5" x="152" y="294">
		<name>io_vin!=null(页面传过来的)</name>
		<if then="2" else="4">
			<expr>io_vin!=null&amp;&amp;!empty(io_vin.trim())</expr>
		</if>
		<parameters></parameters>
		<description></description>
	</decision>
	<logic exception="" id="2" next="6" x="321" y="292">
		<key>crm::/ccioModule/logic/GetCarByCard.logic</key>
		<name>按车载卡获得信息</name>
		<transaction type="supports"></transaction>
		<parameters>
			<parameter id="1" name="saturnData" classType="edu.ccut.saturn.component.SaturnData" passingType="out">
				<value-key>car_saturnData</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="2" name="customer_saturnData" classType="edu.ccut.saturn.component.SaturnData" passingType="out">
				<value-key>customer_saturnData</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="3" name="saturnData" classType="edu.ccut.saturn.component.SaturnData" passingType="out">
				<value-key>member_saturnData</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="4" name="saturnData" classType="edu.ccut.saturn.component.SaturnData" passingType="out">
				<value-key>service_saturnData</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="5" name="saturnData" classType="edu.ccut.saturn.component.SaturnData" passingType="out">
				<value-key>care_saturnData</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="6" name="saturnData" classType="edu.ccut.saturn.component.SaturnData" passingType="out">
				<value-key>jy_saturnData</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="7" name="result" classType="java.util.ArrayList" passingType="out">
				<value-key>oil_result</value-key>
				<scope>2</scope>
				<description>返回SaturnData结果集</description>
			</parameter>
			<parameter id="8" name="saturnData" classType="edu.ccut.saturn.component.SaturnData" passingType="out">
				<value-key>insurance_saturnData</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="9" name="" classType="edu.ccut.saturn.component.SaturnData" passingType="out">
				<value-key>integral_saturnData</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="10" name="b_vin" classType="java.lang.String" passingType="in">
				<value-key>io_vin</value-key>
				<scope>1</scope>
				<description></description>
			</parameter>
			<parameter id="11" name="" classType="edu.ccut.saturn.component.SaturnData" passingType="out">
				<value-key>visit_saturnData</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="12" name="" classType="edu.ccut.saturn.component.SaturnData" passingType="out">
				<value-key>servcare_saturnData</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
		</parameters>
		<description></description>
	</logic>
	<connection source="1" target="5" style="1" name=""></connection>
	<connection source="4" target="3" style="1" name=""></connection>
	<connection source="2" target="6" style="1" name=""></connection>
	<connection source="3" target="2" style="1" name="未命名"></connection>
	<connection source="3" target="6" style="2" name="未命名"></connection>
	<connection source="5" target="4" style="2" name="未命名"></connection>
	<connection source="5" target="2" style="1" name="未命名"></connection>
</saturn-action>