<?xml version="1.0" encoding="UTF-8"?>
<saturn-action>
	<information id="0" next="" x="0" y="0">
		<key>/coreModule/action/CheckUnique.action</key>
		<name>校验唯一项</name>
		<description>校验唯一项</description>
	</information>
	<connection source="3" target="4" style="1" name=""></connection>
	<connection source="6" target="4" style="1" name=""></connection>
	<view id="4" next="" x="620" y="157">
		<name>视图2</name>
		<type>json</type>
		<location>result</location>
		<description></description>
	</view>
	<start id="1" next="5" x="81" y="161">
		<name>开始</name>
		<transaction autorollback="false"></transaction>
		<parameters></parameters>
		<description></description>
	</start>
	<logic exception="" id="2" next="" x="236" y="163">
		<key>crm::/coreModule/logic/CheckUnique.logic</key>
		<name>校验唯一项</name>
		<transaction type="supports"></transaction>
		<parameters>
			<parameter id="1" name="" classType="java.lang.String" passingType="in">
				<value-key>fullkey</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="2" name="" classType="java.lang.String" passingType="in">
				<value-key>carvin</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="3" name="" classType="java.lang.String" passingType="in">
				<value-key>carcardid</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="4" name="" classType="java.lang.String" passingType="in">
				<value-key>membcardid</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="5" name="" classType="java.lang.String" passingType="in">
				<value-key>resvorderid</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="6" name="" classType="java.lang.String" passingType="in">
				<value-key>comptorderid</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="7" name="" classType="java.lang.String" passingType="in">
				<value-key>username</value-key>
				<scope>1</scope>
				<description></description>
			</parameter>
			<parameter id="8" name="target" classType="java.lang.Boolean" passingType="out">
				<value-key>result</value-key>
				<scope>1</scope>
				<description></description>
			</parameter>
		</parameters>
		<description>校验唯一项</description>
	</logic>
	<logic exception="" id="5" next="4" x="328" y="284">
		<key>crm::/coreModule/logic/CheckUnique.logic</key>
		<name>校验唯一项</name>
		<transaction type="supports"></transaction>
		<parameters>
			<parameter id="1" name="fullkey" classType="java.lang.String" passingType="in">
				<value-key>fullkey</value-key>
				<scope>2</scope>
				<description>生成SaturnData所需的Fullkey</description>
			</parameter>
			<parameter id="2" name="" classType="java.lang.String" passingType="in">
				<value-key>carvin</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="3" name="" classType="java.lang.String" passingType="in">
				<value-key>carcardid</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="4" name="" classType="java.lang.String" passingType="in">
				<value-key>membcardid</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="5" name="" classType="java.lang.String" passingType="in">
				<value-key>resvorderid</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="6" name="" classType="java.lang.String" passingType="in">
				<value-key>comptorderid</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="7" name="" classType="java.lang.String" passingType="in">
				<value-key>username</value-key>
				<scope>1</scope>
				<description></description>
			</parameter>
			<parameter id="8" name="target" classType="java.lang.Boolean" passingType="out">
				<value-key>result</value-key>
				<scope>1</scope>
				<description></description>
			</parameter>
			<parameter id="9" name="serv_servorderid" classType="java.lang.String" passingType="in">
				<value-key>serv_servorderid</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="10" name="" classType="java.lang.String" passingType="in">
				<value-key>b_card</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="11" name="" classType="java.lang.String" passingType="in">
				<value-key>b_vin</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="12" name="" classType="java.lang.String" passingType="in">
				<value-key>b_id</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
		</parameters>
		<description>校验唯一项</description>
	</logic>
	<connection source="1" target="5" style="1" name=""></connection>
	<connection source="5" target="4" style="1" name=""></connection>
</saturn-action>