<?xml version="1.0" encoding="UTF-8"?>
<saturn-action>
	<information id="0" next="" x="0" y="0">
		<key>/coreModule/action/GetDictWithHiddenFlag.action</key>
		<name>GetDictWithHiddenFlag</name>
		<description></description>
	</information>
	<start id="1" next="2" x="81" y="161">
		<name>开始</name>
		<transaction autorollback="false"></transaction>
		<parameters></parameters>
		<description></description>
	</start>
	<connection source="4" target="5" style="1" name=""></connection>
	<logic exception="" id="2" next="3" x="284" y="168">
		<key>crm::/coreModule/logic/GetDictWithHiddenFlag.logic</key>
		<name>GetDictWithHiddenFlag</name>
		<transaction type="supports"></transaction>
		<parameters>
			<parameter id="1" name="" classType="java.lang.String" passingType="in">
				<value-key>code</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="2" name="" classType="java.lang.String" passingType="in">
				<value-key>type</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="3" name="" classType="java.lang.String" passingType="in">
				<value-key>value</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="4" name="result" classType="java.util.ArrayList" passingType="out">
				<value-key>list</value-key>
				<scope>1</scope>
				<description>返回SaturnData结果集</description>
			</parameter>
		</parameters>
		<description></description>
	</logic>
	<view id="5" next="" x="712" y="181">
		<name>视图4</name>
		<type>json</type>
		<location>json</location>
		<description></description>
	</view>
	<transform id="3" next="5" x="513" y="177">
		<value-key>json</value-key>
		<type>json</type>
		<name>转移3</name>
		<contents>
			<content id="1" type="data">
				<content-value-key>list</content-value-key>
			</content>
		</contents>
		<description></description>
	</transform>
	<connection source="1" target="2" style="1" name=""></connection>
	<connection source="2" target="3" style="1" name=""></connection>
	<connection source="3" target="5" style="1" name=""></connection>
</saturn-action>