<?xml version="1.0" encoding="UTF-8"?>
<saturn-action>
	<information id="0" next="" x="0" y="0">
		<key>/reportModule/action/ProfitdiffusionNewQuetion.action</key>
		<name>投诉报表导出</name>
		<description></description>
	</information>
	<view id="3" next="" x="426" y="162">
		<name>profitdiffusionnewsquestion</name>
		<type>jsp</type>
		<location>/crm/reportModule/web/profitdiffusionnewsquestion.jsp</location>
		<description></description>
	</view>
	<start id="1" next="2" x="81" y="161">
		<name>开始</name>
		<transaction autorollback="false"></transaction>
		<parameters></parameters>
		<description></description>
	</start>
	<logic exception="" id="2" next="3" x="263" y="165">
		<key>crm::/reportModule/logic/Complaintstatistic.logic</key>
		<name>投诉测算</name>
		<transaction type="supports"></transaction>
		<parameters>
			<parameter id="1" name="statisticdate" classType="java.lang.Object" passingType="in-out">
				<value-key>statisticdate</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="2" name="result" classType="java.util.ArrayList" passingType="out">
				<value-key>resultcomplaintstatisticday</value-key>
				<scope>2</scope>
				<description>返回SaturnData结果集</description>
			</parameter>
			<parameter id="3" name="result" classType="java.util.ArrayList" passingType="out">
				<value-key>resultcomplaintstatisticmon</value-key>
				<scope>2</scope>
				<description>返回SaturnData结果集</description>
			</parameter>
		</parameters>
		<description></description>
	</logic>
	<connection source="1" target="2" style="1" name=""></connection>
	<connection source="2" target="3" style="1" name=""></connection>
</saturn-action>