<?xml version="1.0" encoding="UTF-8"?>
<saturn-action>
	<information id="0" next="" x="0" y="0">
		<key>/oilModule/action/ExportOilList.action</key>
		<name>ExportOilList</name>
		<description></description>
	</information>
	<start id="1" next="2" x="81" y="161">
		<name>开始</name>
		<transaction autorollback="false"></transaction>
		<parameters></parameters>
		<description></description>
	</start>
	<view id="3" next="" x="628" y="203">
		<name>exportOilList</name>
		<type>jsp</type>
		<location>/crm/oilModule/web/exportOilList.jsp</location>
		<description></description>
	</view>
	<logic exception="" id="2" next="3" x="248" y="162">
		<key>crm::/oilModule/logic/ExportOilList.logic</key>
		<name>ExportOilList</name>
		<transaction type="supports"></transaction>
		<parameters>
			<parameter id="1" name="" classType="java.lang.String" passingType="in">
				<value-key>carvin</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="2" name="" classType="java.lang.String" passingType="in">
				<value-key>carcardid</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="3" name="" classType="java.lang.String" passingType="in">
				<value-key>max_oilouttime</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="4" name="" classType="java.lang.String" passingType="in">
				<value-key>min_oilouttime</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="5" name="" classType="java.lang.String" passingType="in">
				<value-key>max_oilstoretime</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="6" name="" classType="java.lang.String" passingType="in">
				<value-key>min_oilstoretime</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="7" name="" classType="java.lang.String" passingType="in">
				<value-key>oilstate</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="8" name="" classType="java.lang.String" passingType="in">
				<value-key>oilstaff</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="9" name="result" classType="java.util.ArrayList" passingType="out">
				<value-key>result</value-key>
				<scope>2</scope>
				<description>返回SaturnData结果集</description>
			</parameter>
			<parameter id="10" name="" classType="java.lang.String" passingType="in">
				<value-key>servorderid</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="11" name="" classType="java.lang.String" passingType="in">
				<value-key>flag</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="12" name="" classType="java.lang.String" passingType="in">
				<value-key>cararea</value-key>
				<scope>1</scope>
				<description></description>
			</parameter>
		</parameters>
		<description></description>
	</logic>
	<connection source="1" target="2" style="1" name=""></connection>
	<connection source="2" target="3" style="1" name=""></connection>
</saturn-action>