<?xml version="1.0" encoding="UTF-8"?>
<saturn-action>
	<information id="0" next="" x="0" y="0">
		<key>/oilModule/action/QueryOilList.action</key>
		<name>查询存油列表</name>
		<description>查询存油列表</description>
	</information>
	<connection source="2" target="3" style="1" name=""></connection>
	<start id="1" next="4" x="81" y="161">
		<name>开始</name>
		<transaction autorollback="false"></transaction>
		<parameters></parameters>
		<description></description>
	</start>
	<view id="3" next="" x="515" y="186">
		<name>oillist</name>
		<type>jsp</type>
		<location>/crm/oilModule/web/oillist.jsp</location>
		<description></description>
	</view>
	<logic exception="" id="4" next="3" x="275" y="182">
		<key>crm::/oilModule/logic/QueryOilList.logic</key>
		<name>查询存油列表</name>
		<transaction type="supports"></transaction>
		<parameters>
			<parameter id="1" name="" classType="java.lang.String" passingType="in-out">
				<value-key>min_oilstoretime</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="2" name="" classType="java.lang.String" passingType="in-out">
				<value-key>max_oilstoretime</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="3" name="" classType="java.lang.String" passingType="in-out">
				<value-key>carlicenceno</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="4" name="" classType="java.lang.String" passingType="in-out">
				<value-key>carcardid</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="5" name="" classType="java.lang.String" passingType="in-out">
				<value-key>carvin</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="6" name="" classType="java.lang.String" passingType="in-out">
				<value-key>carbrand</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="7" name="" classType="java.lang.String" passingType="in-out">
				<value-key>carseries</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="8" name="" classType="java.lang.String" passingType="in-out">
				<value-key>carmodel</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="9" name="" classType="java.lang.String" passingType="in-out">
				<value-key>cstmname</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="10" name="" classType="java.lang.String" passingType="in-out">
				<value-key>oilstaff</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="11" name="" classType="java.lang.String" passingType="in-out">
				<value-key>max_oilouttime</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="12" name="" classType="java.lang.String" passingType="in-out">
				<value-key>min_oilouttime</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="13" name="" classType="java.lang.String" passingType="in-out">
				<value-key>oilstate</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="14" name="" classType="java.lang.String" passingType="in">
				<value-key>startIndex</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="15" name="" classType="java.lang.String" passingType="in">
				<value-key>endIndex</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="16" name="count" classType="java.lang.String" passingType="out">
				<value-key>count</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="17" name="result" classType="java.util.ArrayList" passingType="out">
				<value-key>result</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="18" name="" classType="java.lang.String" passingType="in-out">
				<value-key>servorderid</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="19" name="" classType="java.lang.String" passingType="in-out">
				<value-key>flag</value-key>
				<scope>1</scope>
				<description></description>
			</parameter>
			<parameter id="20" name="cararea" classType="java.lang.String" passingType="in-out">
				<value-key>cararea</value-key>
				<scope>1</scope>
				<description></description>
			</parameter>
		</parameters>
		<description>查询存油列表</description>
	</logic>
	<connection source="1" target="4" style="1" name=""></connection>
	<connection source="4" target="3" style="1" name=""></connection>
</saturn-action>