INSERT INTO app_dict(`key`, `value`, `type`, pinyin) VALUES
 ('非农', '非农', 'sldb.hukou', 'none')
, ('农业', '农业', 'sldb.hukou', 'none')

,('其他', '其他', 'sldb.home', 'none')
,('农转非家庭', '农转非家庭', 'sldb.home', 'none')
,('因残致贫家庭', '因残致贫家庭', 'sldb.home', 'none')
,('年老体弱家庭', '年老体弱家庭', 'sldb.home', 'none')
,('子女就学（升学）困难家庭', '子女就学（升学）困难家庭', 'sldb.home', 'none')
,('因灾致贫家庭', '因灾致贫家庭', 'sldb.home', 'none')
,('因病致贫家庭', '因病致贫家庭', 'sldb.home', 'none')
,('三无人员家庭', '三无人员家庭', 'sldb.home', 'none')

,('丧偶', '丧偶', 'sldb.marry', 'none')
,('离异', '离异', 'sldb.marry', 'none')
,('未婚', '未婚', 'sldb.marry', 'none')
,('已婚', '已婚', 'sldb.marry', 'none')

,('完全劳动能力', '完全劳动能力', 'sldb.workable', 'none')
,('部分劳动能力', '部分劳动能力', 'sldb.workable', 'none')
,('无劳动能力', '无劳动能力', 'sldb.workable', 'none')

,('其他', '其他', 'sldb.idType', 'none')
,('孤儿', '孤儿', 'sldb.idType', 'none')
,('大学在校生', '大学在校生', 'sldb.idType', 'none')
,('高中在校生', '高中在校生', 'sldb.idType', 'none')
,('中学在校生', '中学在校生', 'sldb.idType', 'none')
,('小学在校生', '小学在校生', 'sldb.idType', 'none')
,('无业', '无业', 'sldb.idType', 'none')
,('退休', '退休', 'sldb.idType', 'none')
,('在职', '在职', 'sldb.idType', 'none')

,('其他特殊病种', '其他特殊病种', 'sldb.ill', 'none')
,('红斑狼疮', '红斑狼疮', 'sldb.ill', 'none')
,('腰间盘突出', '腰间盘突出', 'sldb.ill', 'none')
,('股骨头坏死', '股骨头坏死', 'sldb.ill', 'none')
,('气管炎', '气管炎', 'sldb.ill', 'none')
,('哮喘', '哮喘', 'sldb.ill', 'none')
,('精神病', '精神病', 'sldb.ill', 'none')
,('肺结核', '肺结核', 'sldb.ill', 'none')
,('白血病', '白血病', 'sldb.ill', 'none')
,('类风湿疾病', '类风湿疾病', 'sldb.ill', 'none')
,('糖尿病', '糖尿病', 'sldb.ill', 'none')
,('重症肝病', '重症肝病', 'sldb.ill', 'none')
,('脑血栓', '脑血栓', 'sldb.ill', 'none')
,('脑出血', '脑出血', 'sldb.ill', 'none')
,('心脏病', '心脏病', 'sldb.ill', 'none')
,('肾功能衰竭', '肾功能衰竭', 'sldb.ill', 'none')
,('癌症', '癌症', 'sldb.ill', 'none')

,('其他残疾', '其他残疾', 'sldb.deformity', 'none')
,('多重残疾', '多重残疾', 'sldb.deformity', 'none')
,('精神残疾', '精神残疾', 'sldb.deformity', 'none')
,('智力残疾', '智力残疾', 'sldb.deformity', 'none')
,('肢体残疾', '肢体残疾', 'sldb.deformity', 'none')
,('言语残疾', '言语残疾', 'sldb.deformity', 'none')
,('听力残疾', '听力残疾', 'sldb.deformity', 'none')
,('视力残疾', '视力残疾', 'sldb.deformity', 'none')

,('一级', '一级', 'sldb.deformityLevel', 'none')
,('二级', '二级', 'sldb.deformityLevel', 'none')
,('三级', '三级', 'sldb.deformityLevel', 'none')
,('四级', '四级', 'sldb.deformityLevel', 'none')
,('五级', '五级', 'sldb.deformityLevel', 'none')

,('其他', '其他', 'sldb.companyType', 'none')
,('地方集体', '地方集体', 'sldb.companyType', 'none')
,('地方国有', '地方国有', 'sldb.companyType', 'none')
,('省直集体', '省直集体', 'sldb.companyType', 'none')
,('省直国有', '省直国有', 'sldb.companyType', 'none')
,('中直集体', '中直集体', 'sldb.companyType', 'none')
,('中直国有', '中直国有', 'sldb.companyType', 'none')

,('其他', '其他', 'sldb.trade', 'none')
,('轻化', '轻化', 'sldb.trade', 'none')
,('建筑', '建筑', 'sldb.trade', 'none')
,('地矿', '地矿', 'sldb.trade', 'none')
,('机械军工', '机械军工', 'sldb.trade', 'none')
,('农垦', '农垦', 'sldb.trade', 'none')
,('冶金', '冶金', 'sldb.trade', 'none')
,('森工', '森工', 'sldb.trade', 'none')
,('煤炭', '煤炭', 'sldb.trade', 'none')

,('其他保险', '其他保险', 'sldb.insurance', 'none')
,('商业保险', '商业保险', 'sldb.insurance', 'none')
,('工伤保险', '工伤保险', 'sldb.insurance', 'none')
,('生育保险', '生育保险', 'sldb.insurance', 'none')
,('失业保险', '失业保险', 'sldb.insurance', 'none')
,('医疗保险', '医疗保险', 'sldb.insurance', 'none')
,('养老保险', '养老保险', 'sldb.insurance', 'none')
,('否', '否', 'sldb.insurance', 'none')