<?xml version="1.0" encoding="UTF-8"?>
<saturn-action>
	<information id="0" next="" x="0" y="0">
		<key>/dutyModule/action/DutyReport.action</key>
		<name>总值日报</name>
		<description></description>
	</information>
	<start id="1" next="3" x="81" y="161">
		<name>开始</name>
		<transaction autorollback="false"></transaction>
		<parameters></parameters>
		<description></description>
	</start>
	<decision next="" id="4" x="430" y="275">
		<name>'excel'==op</name>
		<if then="5" else="2">
			<expr>'excel'==op</expr>
		</if>
		<parameters></parameters>
		<description></description>
	</decision>
	<logic exception="" id="3" next="4" x="260" y="196">
		<key>crm::/dutyModule/logic/DutyReport.logic</key>
		<name>总值日报</name>
		<transaction type="supports"></transaction>
		<parameters>
			<parameter id="1" name="result" classType="java.util.ArrayList" passingType="out">
				<value-key>oneresult</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="2" name="" classType="java.util.ArrayList" passingType="out">
				<value-key>tworesult</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="3" name="" classType="java.util.ArrayList" passingType="out">
				<value-key>threeresult</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="4" name="dutyintime" classType="java.lang.String" passingType="in">
				<value-key>dutyintime</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
		</parameters>
		<description></description>
	</logic>
	<view id="5" next="" x="528" y="379">
		<name>dutyreportexcel</name>
		<type>jsp</type>
		<location>/crm/dutyModule/web/dutyreportexcel.jsp</location>
		<description></description>
	</view>
	<view id="2" next="" x="505" y="181">
		<name>dutyreport</name>
		<type>jsp</type>
		<location>/crm/dutyModule/web/dutyreport.jsp</location>
		<description></description>
	</view>
	<connection source="1" target="3" style="1" name=""></connection>
	<connection source="3" target="4" style="1" name=""></connection>
	<connection source="4" target="2" style="2" name="未命名"></connection>
	<connection source="4" target="5" style="1" name="未命名"></connection>
</saturn-action>