<?xml version="1.0" encoding="UTF-8"?>
<saturn-action>
	<information id="0" next="" x="0" y="0">
		<key>/dutyModule/action/QueryDutyList.action</key>
		<name>总值信息列表</name>
		<description></description>
	</information>
	<connection source="2" target="3" style="1" name=""></connection>
	<connection source="4" target="3" style="1" name=""></connection>
	<view id="3" next="" x="488" y="167">
		<name>dutyList</name>
		<type>jsp</type>
		<location>/crm/dutyModule/web/dutyList.jsp</location>
		<description></description>
	</view>
	<start id="1" next="5" x="81" y="161">
		<name>开始</name>
		<transaction autorollback="false"></transaction>
		<parameters></parameters>
		<description></description>
	</start>
	<logic exception="" id="5" next="3" x="248" y="146">
		<key>crm::/dutyModule/logic/QueryDutyList.logic</key>
		<name>总值信息列表</name>
		<transaction type="supports"></transaction>
		<parameters>
			<parameter id="1" name="" classType="java.lang.String" passingType="in-out">
				<value-key>carlicenseno</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="2" name="" classType="java.lang.String" passingType="in-out">
				<value-key>min_dutyintime</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="3" name="" classType="java.lang.String" passingType="in-out">
				<value-key>max_dutyintime</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="4" name="" classType="java.lang.String" passingType="in-out">
				<value-key>dutycarmodel</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="5" name="" classType="java.lang.String" passingType="in-out">
				<value-key>min_dutydelivtime</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="6" name="" classType="java.lang.String" passingType="in-out">
				<value-key>max_dutydelivtime</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="7" name="count" classType="java.lang.Integer" passingType="out">
				<value-key>count</value-key>
				<scope>2</scope>
				<description>记录条数</description>
			</parameter>
			<parameter id="8" name="list" classType="java.util.ArrayList" passingType="in-out">
				<value-key>result</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="9" name="startIndex" classType="java.lang.Integer" passingType="in">
				<value-key>startIndex</value-key>
				<scope>2</scope>
				<description>分页开始位置</description>
			</parameter>
			<parameter id="10" name="endIndex" classType="java.lang.Integer" passingType="in">
				<value-key>endIndex</value-key>
				<scope>2</scope>
				<description>分页结束位置</description>
			</parameter>
			<parameter id="11" name="" classType="java.lang.String" passingType="in">
				<value-key>carvin</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="12" name="carcardid" classType="java.lang.String" passingType="in">
				<value-key>carcardid</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="13" name="dutytype" classType="java.lang.String" passingType="in">
				<value-key>dutytype</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="14" name="dutystaff" classType="java.lang.String" passingType="in">
				<value-key>dutystaff</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="15" name="" classType="java.lang.String" passingType="in">
				<value-key>dutydelivtime</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="16" name="dutycommu" classType="java.lang.String" passingType="in">
				<value-key>dutycommu</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
		</parameters>
		<description></description>
	</logic>
	<connection source="1" target="5" style="1" name=""></connection>
	<connection source="5" target="3" style="1" name=""></connection>
</saturn-action>