INSERT INTO web_content(id, name, english, path, hasShow, hasShowName, mode, modeName) 
VALUES
('xinyu', '通化鑫宇汽车销售有限公司', 'JiLin LongFu', '', 'visible.true', '显示', 'content.mode.one', '单项');

INSERT INTO web_content(id, name, english, path, parentId, hasShow, hasShowName, mode, modeName) 
VALUES

 ('xinyu.home', '首页', 'Home', 'index.jsp', 'xinyu', 'visible.true', '显示', 'content.mode.one', '单项')
,('xinyu.about', '企业介绍', 'About', '', 'xinyu', 'visible.true', '显示', 'content.mode.one', '单项')
,('xinyu.new', '新闻中心', 'New', '', 'xinyu', 'visible.true', '显示', 'content.mode.more', '多项')
,('xinyu.sall', '销售服务', 'Sall', '', 'xinyu', 'visible.true', '显示', 'content.mode.one', '单项')
,('xinyu.salled', '售后服务', 'Salled', '', 'xinyu', 'visible.true', '显示', 'content.mode.one', '单项')
,('xinyu.insurance', '保险服务', 'Insurance', '', 'xinyu', 'visible.true', '显示', 'content.mode.one', '单项')
,('xinyu.online', '在线客服', 'Online', '', 'xinyu', 'visible.true', '显示', 'content.mode.one', '单项')
,('xinyu.book', '预约服务', 'Book', '', 'xinyu', 'visible.true', '显示', 'content.mode.one', '单项')
,('xinyu.about.introduce', '企业介绍', 'Introduce', '', 'xinyu.about', 'visible.true', '显示', 'content.mode.one', '单项')
,('xinyu.about.glory', '公司荣誉', 'Glory', '', 'xinyu.about', 'visible.true', '显示', 'content.mode.one', '单项')
,('xinyu.about.form', '公司形象', 'Form', '', 'xinyu.about', 'visible.true', '显示', 'content.mode.one', '单项')
,('xinyu.about.contact', '联系方式', 'Contact', '', 'xinyu.about', 'visible.true', '显示', 'content.mode.one', '单项')
,('xinyu.new.offsall', '优惠活动', 'OffSall', '', 'xinyu.new', 'visible.true', '显示', 'content.mode.more', '多项')
,('xinyu.new.company', '公司新闻', 'Company', '', 'xinyu.new', 'visible.true', '显示', 'content.mode.more', '多项')
,('xinyu.new.car', '行业新闻', 'Car', '', 'xinyu.new', 'visible.true', '显示', 'content.mode.more', '多项')
,('xinyu.sall.new', '新车报价', 'NewCar', '', 'xinyu.sall', 'visible.true', '显示', 'content.mode.one', '单项')
,('xinyu.sall.offsall', '优惠促销', 'OffSall', '', 'xinyu.sall', 'visible.true', '显示', 'content.mode.one', '单项')
,('xinyu.sall.special', '特色服务', 'Special', '', 'xinyu.sall', 'visible.true', '显示', 'content.mode.one', '单项')
,('xinyu.salled.notice', '公告', 'Notice', '', 'xinyu.salled', 'visible.true', '显示', 'content.mode.one', '单项')
,('xinyu.salled.repair', '保修保养服务', 'Repair', '', 'xinyu.salled', 'visible.true', '显示', 'content.mode.one', '单项')
,('xinyu.salled.special', '特色服务', 'Special', '', 'xinyu.salled', 'visible.true', '显示', 'content.mode.one', '单项')
,('xinyu.salled.help', '服务手册', 'Help', '', 'xinyu.salled', 'visible.true', '显示', 'content.mode.one', '单项')
,('xinyu.insurance.introduce', '保险服务介绍', 'Introduce', '', 'xinyu.insurance', 'visible.true', '显示', 'content.mode.one', '单项')
,('xinyu.insurance.knowledge', '保险知识', 'Knowledge', '', 'xinyu.insurance', 'visible.true', '显示', 'content.mode.one', '单项')
,('xinyu.insurance.indemnify', '保险理赔', 'Insurance', '', 'xinyu.insurance', 'visible.true', '显示', 'content.mode.one', '单项')
,('xinyu.online.enquire', '资讯客服', 'Enquire', '', 'xinyu.online', 'visible.true', '显示', 'content.mode.one', '单项')
,('xinyu.online.complain', '投诉意见', 'Complain', 'cus_advise.jsp', 'xinyu.online', 'visible.true', '显示', 'content.mode.one', '单项')
,('xinyu.online.message', '客户留言', 'Message', 'cus_message.jsp', 'xinyu.online', 'visible.true', '显示', 'content.mode.one', '单项')
,('xinyu.book.drive', '试乘预约', 'Drive', '', 'xinyu.book', 'visible.true', '显示', 'content.mode.one', '单项')
,('xinyu.book.repair', '维修预约', 'Repair', '', 'xinyu.book', 'visible.true', '显示', 'content.mode.one', '单项')
,('xinyu.book.maintain', '保养预约', 'Maintain', '', 'xinyu.book', 'visible.true', '显示', 'content.mode.one', '单项')
,('xinyu.book.buy', '订车预约', 'Buy', '', 'xinyu.book', 'visible.true', '显示', 'content.mode.one', '单项')
;