INSERT INTO web_content(id, name, english, path, hasShow, hasShowName, mode, modeName) 
VALUES
('xuefulan', '雪弗兰4S店', 'XueFuLan', '', 'visible.true', '显示', 'content.mode.one', '单项');

INSERT INTO web_content(id, name, english, path, parentId, hasShow, hasShowName, mode, modeName) 
VALUES

 ('xuefulan.home', '首页', 'Home', '', 'xuefulan', 'visible.true', '显示', 'content.mode.one', '单项')
,('xuefulan.about', '企业介绍', 'About', '', 'xuefulan', 'visible.true', '显示', 'content.mode.one', '单项')
,('xuefulan.new', '新闻中心', 'New', '', 'xuefulan', 'visible.true', '显示', 'content.mode.more', '多项')
,('xuefulan.sall', '销售服务', 'Sall', '', 'xuefulan', 'visible.true', '显示', 'content.mode.one', '单项')
,('xuefulan.salled', '售后服务', 'Salled', '', 'xuefulan', 'visible.true', '显示', 'content.mode.one', '单项')
,('xuefulan.insurance', '保险服务', 'Insurance', '', 'xuefulan', 'visible.true', '显示', 'content.mode.one', '单项')
,('xuefulan.online', '在线客服', 'Online', '', 'xuefulan', 'visible.true', '显示', 'content.mode.one', '单项')
,('xuefulan.book', '预约服务', 'Book', '', 'xuefulan', 'visible.true', '显示', 'content.mode.one', '单项')
,('xuefulan.about.introduce', '企业介绍', 'Introduce', '', 'xuefulan.about', 'visible.true', '显示', 'content.mode.one', '单项')
,('xuefulan.about.glory', '公司荣誉', 'Glory', '', 'xuefulan.about', 'visible.true', '显示', 'content.mode.one', '单项')
,('xuefulan.about.form', '公司形象', 'Form', '', 'xuefulan.about', 'visible.true', '显示', 'content.mode.one', '单项')
,('xuefulan.about.contact', '联系方式', 'Contact', '', 'xuefulan.about', 'visible.true', '显示', 'content.mode.one', '单项')
,('xuefulan.new.offsall', '优惠活动', 'OffSall', '', 'xuefulan.new', 'visible.true', '显示', 'content.mode.more', '多项')
,('xuefulan.new.company', '公司新闻', 'Company', '', 'xuefulan.new', 'visible.true', '显示', 'content.mode.more', '多项')
,('xuefulan.new.car', '行业新闻', 'Car', '', 'xuefulan.new', 'visible.true', '显示', 'content.mode.more', '多项')
,('xuefulan.sall.new', '新车报价', 'NewCar', '', 'xuefulan.sall', 'visible.true', '显示', 'content.mode.one', '单项')
,('xuefulan.sall.offsall', '优惠促销', 'OffSall', '', 'xuefulan.sall', 'visible.true', '显示', 'content.mode.one', '单项')
,('xuefulan.sall.special', '特色服务', 'Special', '', 'xuefulan.sall', 'visible.true', '显示', 'content.mode.one', '单项')
,('xuefulan.salled.notice', '公告', 'Notice', '', 'xuefulan.salled', 'visible.true', '显示', 'content.mode.one', '单项')
,('xuefulan.salled.repair', '保修保养服务', 'Repair', '', 'xuefulan.salled', 'visible.true', '显示', 'content.mode.one', '单项')
,('xuefulan.salled.special', '特色服务', 'Special', '', 'xuefulan.salled', 'visible.true', '显示', 'content.mode.one', '单项')
,('xuefulan.salled.help', '服务手册', 'Help', '', 'xuefulan.salled', 'visible.true', '显示', 'content.mode.one', '单项')
,('xuefulan.insurance.introduce', '保险服务介绍', 'Introduce', '', 'xuefulan.insurance', 'visible.true', '显示', 'content.mode.one', '单项')
,('xuefulan.insurance.knowledge', '保险知识', 'Knowledge', '', 'xuefulan.insurance', 'visible.true', '显示', 'content.mode.one', '单项')
,('xuefulan.insurance.indemnify', '保险理赔', 'Insurance', '', 'xuefulan.insurance', 'visible.true', '显示', 'content.mode.one', '单项')
,('xuefulan.online.enquire', '资讯客服', 'Enquire', '', 'xuefulan.online', 'visible.true', '显示', 'content.mode.one', '单项')
,('xuefulan.online.complain', '投诉意见', 'Complain', '', 'xuefulan.online', 'visible.true', '显示', 'content.mode.one', '单项')
,('xuefulan.online.message', '客户留言', 'Message', '', 'xuefulan.online', 'visible.true', '显示', 'content.mode.one', '单项')
,('xuefulan.book.drive', '试乘预约', 'Drive', '', 'xuefulan.book', 'visible.true', '显示', 'content.mode.one', '单项')
,('xuefulan.book.repair', '维修预约', 'Repair', '', 'xuefulan.book', 'visible.true', '显示', 'content.mode.one', '单项')
,('xuefulan.book.maintain', '保养预约', 'Maintain', '', 'xuefulan.book', 'visible.true', '显示', 'content.mode.one', '单项')
,('xuefulan.book.buy', '订车预约', 'Buy', '', 'xuefulan.book', 'visible.true', '显示', 'content.mode.one', '单项')
;