INSERT INTO web_content(id, name, english, path, hasShow, hasShowName, mode, modeName) 
VALUES
('honda', '东风本田4S店', 'DongFengBenTian', '', 'visible.true', '显示', 'content.mode.one', '单项');

INSERT INTO web_content(id, name, english, path, parentId, hasShow, hasShowName, mode, modeName) 
VALUES

 ('honda.home', '首页', 'Home', '', 'honda', 'visible.true', '显示', 'content.mode.one', '单项')
,('honda.about', '企业介绍', 'About', '', 'honda', 'visible.true', '显示', 'content.mode.one', '单项')
,('honda.new', '新闻中心', 'New', '', 'honda', 'visible.true', '显示', 'content.mode.more', '多项')
,('honda.sall', '销售服务', 'Sall', '', 'honda', 'visible.true', '显示', 'content.mode.one', '单项')
,('honda.salled', '售后服务', 'Salled', '', 'honda', 'visible.true', '显示', 'content.mode.one', '单项')
,('honda.insurance', '保险服务', 'Insurance', '', 'honda', 'visible.true', '显示', 'content.mode.one', '单项')
,('honda.online', '在线客服', 'Online', '', 'honda', 'visible.true', '显示', 'content.mode.one', '单项')
,('honda.book', '预约服务', 'Book', '', 'honda', 'visible.true', '显示', 'content.mode.one', '单项')
,('honda.about.introduce', '企业介绍', 'Introduce', '', 'honda.about', 'visible.true', '显示', 'content.mode.one', '单项')
,('honda.about.glory', '公司荣誉', 'Glory', '', 'honda.about', 'visible.true', '显示', 'content.mode.one', '单项')
,('honda.about.form', '公司形象', 'Form', '', 'honda.about', 'visible.true', '显示', 'content.mode.one', '单项')
,('honda.about.contact', '联系方式', 'Contact', '', 'honda.about', 'visible.true', '显示', 'content.mode.one', '单项')
,('honda.new.offsall', '优惠活动', 'OffSall', '', 'honda.new', 'visible.true', '显示', 'content.mode.more', '多项')
,('honda.new.company', '公司新闻', 'Company', '', 'honda.new', 'visible.true', '显示', 'content.mode.more', '多项')
,('honda.new.car', '行业新闻', 'Car', '', 'honda.new', 'visible.true', '显示', 'content.mode.more', '多项')
,('honda.sall.new', '新车报价', 'NewCar', '', 'honda.sall', 'visible.true', '显示', 'content.mode.one', '单项')
,('honda.sall.offsall', '优惠促销', 'OffSall', '', 'honda.sall', 'visible.true', '显示', 'content.mode.one', '单项')
,('honda.sall.special', '特色服务', 'Special', '', 'honda.sall', 'visible.true', '显示', 'content.mode.one', '单项')
,('honda.salled.notice', '公告', 'Notice', '', 'honda.salled', 'visible.true', '显示', 'content.mode.one', '单项')
,('honda.salled.repair', '保修保养服务', 'Repair', '', 'honda.salled', 'visible.true', '显示', 'content.mode.one', '单项')
,('honda.salled.special', '特色服务', 'Special', '', 'honda.salled', 'visible.true', '显示', 'content.mode.one', '单项')
,('honda.salled.help', '服务手册', 'Help', '', 'honda.salled', 'visible.true', '显示', 'content.mode.one', '单项')
,('honda.insurance.introduce', '保险服务介绍', 'Introduce', '', 'honda.insurance', 'visible.true', '显示', 'content.mode.one', '单项')
,('honda.insurance.knowledge', '保险知识', 'Knowledge', '', 'honda.insurance', 'visible.true', '显示', 'content.mode.one', '单项')
,('honda.insurance.indemnify', '保险理赔', 'Insurance', '', 'honda.insurance', 'visible.true', '显示', 'content.mode.one', '单项')
,('honda.online.enquire', '资讯客服', 'Enquire', '', 'honda.online', 'visible.true', '显示', 'content.mode.one', '单项')
,('honda.online.complain', '投诉意见', 'Complain', '', 'honda.online', 'visible.true', '显示', 'content.mode.one', '单项')
,('honda.online.message', '客户留言', 'Message', '', 'honda.online', 'visible.true', '显示', 'content.mode.one', '单项')
,('honda.book.drive', '试乘预约', 'Drive', '', 'honda.book', 'visible.true', '显示', 'content.mode.one', '单项')
,('honda.book.repair', '维修预约', 'Repair', '', 'honda.book', 'visible.true', '显示', 'content.mode.one', '单项')
,('honda.book.maintain', '保养预约', 'Maintain', '', 'honda.book', 'visible.true', '显示', 'content.mode.one', '单项')
,('honda.book.buy', '订车预约', 'Buy', '', 'honda.book', 'visible.true', '显示', 'content.mode.one', '单项')
;