INSERT INTO web_content(id, name, english, path, hasShow, hasShowName, mode, modeName) 
VALUES
('infiniti', '长春融展英菲尼迪', 'ChangChun RuiFu', '', 'visible.true', '显示', 'content.mode.one', '单项');

INSERT INTO web_content(id, name, english, path, parentId, hasShow, hasShowName, mode, modeName) 
VALUES

 ('infiniti.home', '首页', 'Home', '', 'infiniti', 'visible.true', '显示', 'content.mode.one', '单项')
,('infiniti.about', '企业介绍', 'About', '', 'infiniti', 'visible.true', '显示', 'content.mode.one', '单项')
,('infiniti.new', '新闻中心', 'New', '', 'infiniti', 'visible.true', '显示', 'content.mode.more', '多项')
,('infiniti.sall', '销售服务', 'Sall', '', 'infiniti', 'visible.true', '显示', 'content.mode.one', '单项')
,('infiniti.salled', '售后服务', 'Salled', '', 'infiniti', 'visible.true', '显示', 'content.mode.one', '单项')
,('infiniti.insurance', '保险服务', 'Insurance', '', 'infiniti', 'visible.true', '显示', 'content.mode.one', '单项')
,('infiniti.online', '在线客服', 'Online', '', 'infiniti', 'visible.true', '显示', 'content.mode.one', '单项')
,('infiniti.book', '预约服务', 'Book', '', 'infiniti', 'visible.true', '显示', 'content.mode.one', '单项')
,('infiniti.about.introduce', '企业介绍', 'Introduce', '', 'infiniti.about', 'visible.true', '显示', 'content.mode.one', '单项')
,('infiniti.about.glory', '公司荣誉', 'Glory', '', 'infiniti.about', 'visible.true', '显示', 'content.mode.one', '单项')
,('infiniti.about.form', '公司形象', 'Form', '', 'infiniti.about', 'visible.true', '显示', 'content.mode.one', '单项')
,('infiniti.about.contact', '联系方式', 'Contact', '', 'infiniti.about', 'visible.true', '显示', 'content.mode.one', '单项')
,('infiniti.new.offsall', '优惠活动', 'OffSall', '', 'infiniti.new', 'visible.true', '显示', 'content.mode.more', '多项')
,('infiniti.new.company', '公司新闻', 'Company', '', 'infiniti.new', 'visible.true', '显示', 'content.mode.more', '多项')
,('infiniti.new.car', '行业新闻', 'Car', '', 'infiniti.new', 'visible.true', '显示', 'content.mode.more', '多项')
,('infiniti.sall.new', '新车报价', 'NewCar', '', 'infiniti.sall', 'visible.true', '显示', 'content.mode.one', '单项')
,('infiniti.sall.offsall', '优惠促销', 'OffSall', '', 'infiniti.sall', 'visible.true', '显示', 'content.mode.one', '单项')
,('infiniti.sall.special', '特色服务', 'Special', '', 'infiniti.sall', 'visible.true', '显示', 'content.mode.one', '单项')
,('infiniti.salled.notice', '公告', 'Notice', '', 'infiniti.salled', 'visible.true', '显示', 'content.mode.one', '单项')
,('infiniti.salled.repair', '保修保养服务', 'Repair', '', 'infiniti.salled', 'visible.true', '显示', 'content.mode.one', '单项')
,('infiniti.salled.special', '特色服务', 'Special', '', 'infiniti.salled', 'visible.true', '显示', 'content.mode.one', '单项')
,('infiniti.salled.help', '服务手册', 'Help', '', 'infiniti.salled', 'visible.true', '显示', 'content.mode.one', '单项')
,('infiniti.insurance.introduce', '保险服务介绍', 'Introduce', '', 'infiniti.insurance', 'visible.true', '显示', 'content.mode.one', '单项')
,('infiniti.insurance.knowledge', '保险知识', 'Knowledge', '', 'infiniti.insurance', 'visible.true', '显示', 'content.mode.one', '单项')
,('infiniti.insurance.indemnify', '保险理赔', 'Insurance', '', 'infiniti.insurance', 'visible.true', '显示', 'content.mode.one', '单项')
,('infiniti.online.enquire', '资讯客服', 'Enquire', '', 'infiniti.online', 'visible.true', '显示', 'content.mode.one', '单项')
,('infiniti.online.complain', '投诉意见', 'Complain', '', 'infiniti.online', 'visible.true', '显示', 'content.mode.one', '单项')
,('infiniti.online.message', '客户留言', 'Message', '', 'infiniti.online', 'visible.true', '显示', 'content.mode.one', '单项')
,('infiniti.book.drive', '试乘预约', 'Drive', '', 'infiniti.book', 'visible.true', '显示', 'content.mode.one', '单项')
,('infiniti.book.repair', '维修预约', 'Repair', '', 'infiniti.book', 'visible.true', '显示', 'content.mode.one', '单项')
,('infiniti.book.maintain', '保养预约', 'Maintain', '', 'infiniti.book', 'visible.true', '显示', 'content.mode.one', '单项')
,('infiniti.book.buy', '订车预约', 'Buy', '', 'infiniti.book', 'visible.true', '显示', 'content.mode.one', '单项')
;