INSERT INTO web_content(id, name, english, path, hasShow, hasShowName, mode, modeName) 
VALUES
('rongsheng', '通化市融晟汽车销售服务有限公司', 'JiLin LongFu', '', 'visible.true', '显示', 'content.mode.one', '单项');

INSERT INTO web_content(id, name, english, path, parentId, hasShow, hasShowName, mode, modeName) 
VALUES

 ('rongsheng.home', '首页', 'Home', 'index.jsp', 'rongsheng', 'visible.true', '显示', 'content.mode.one', '单项')
,('rongsheng.about', '企业介绍', 'About', '', 'rongsheng', 'visible.true', '显示', 'content.mode.one', '单项')
,('rongsheng.new', '新闻中心', 'New', '', 'rongsheng', 'visible.true', '显示', 'content.mode.more', '多项')
,('rongsheng.sall', '销售服务', 'Sall', '', 'rongsheng', 'visible.true', '显示', 'content.mode.one', '单项')
,('rongsheng.salled', '售后服务', 'Salled', '', 'rongsheng', 'visible.true', '显示', 'content.mode.one', '单项')
,('rongsheng.insurance', '保险服务', 'Insurance', '', 'rongsheng', 'visible.true', '显示', 'content.mode.one', '单项')
,('rongsheng.online', '在线客服', 'Online', '', 'rongsheng', 'visible.true', '显示', 'content.mode.one', '单项')
,('rongsheng.book', '预约服务', 'Book', '', 'rongsheng', 'visible.true', '显示', 'content.mode.one', '单项')
,('rongsheng.about.introduce', '企业介绍', 'Introduce', '', 'rongsheng.about', 'visible.true', '显示', 'content.mode.one', '单项')
,('rongsheng.about.glory', '公司荣誉', 'Glory', '', 'rongsheng.about', 'visible.true', '显示', 'content.mode.one', '单项')
,('rongsheng.about.form', '公司形象', 'Form', '', 'rongsheng.about', 'visible.true', '显示', 'content.mode.one', '单项')
,('rongsheng.about.contact', '联系方式', 'Contact', '', 'rongsheng.about', 'visible.true', '显示', 'content.mode.one', '单项')
,('rongsheng.new.offsall', '优惠活动', 'OffSall', '', 'rongsheng.new', 'visible.true', '显示', 'content.mode.more', '多项')
,('rongsheng.new.company', '公司新闻', 'Company', '', 'rongsheng.new', 'visible.true', '显示', 'content.mode.more', '多项')
,('rongsheng.new.car', '行业新闻', 'Car', '', 'rongsheng.new', 'visible.true', '显示', 'content.mode.more', '多项')
,('rongsheng.sall.new', '新车报价', 'NewCar', '', 'rongsheng.sall', 'visible.true', '显示', 'content.mode.one', '单项')
,('rongsheng.sall.offsall', '优惠促销', 'OffSall', '', 'rongsheng.sall', 'visible.true', '显示', 'content.mode.one', '单项')
,('rongsheng.sall.special', '特色服务', 'Special', '', 'rongsheng.sall', 'visible.true', '显示', 'content.mode.one', '单项')
,('rongsheng.salled.notice', '公告', 'Notice', '', 'rongsheng.salled', 'visible.true', '显示', 'content.mode.one', '单项')
,('rongsheng.salled.repair', '保修保养服务', 'Repair', '', 'rongsheng.salled', 'visible.true', '显示', 'content.mode.one', '单项')
,('rongsheng.salled.special', '特色服务', 'Special', '', 'rongsheng.salled', 'visible.true', '显示', 'content.mode.one', '单项')
,('rongsheng.salled.help', '服务手册', 'Help', '', 'rongsheng.salled', 'visible.true', '显示', 'content.mode.one', '单项')
,('rongsheng.insurance.introduce', '保险服务介绍', 'Introduce', '', 'rongsheng.insurance', 'visible.true', '显示', 'content.mode.one', '单项')
,('rongsheng.insurance.knowledge', '保险知识', 'Knowledge', '', 'rongsheng.insurance', 'visible.true', '显示', 'content.mode.one', '单项')
,('rongsheng.insurance.indemnify', '保险理赔', 'Insurance', '', 'rongsheng.insurance', 'visible.true', '显示', 'content.mode.one', '单项')
,('rongsheng.online.enquire', '资讯客服', 'Enquire', '', 'rongsheng.online', 'visible.true', '显示', 'content.mode.one', '单项')
,('rongsheng.online.complain', '投诉意见', 'Complain', 'cus_advise.jsp', 'rongsheng.online', 'visible.true', '显示', 'content.mode.one', '单项')
,('rongsheng.online.message', '客户留言', 'Message', 'cus_message.jsp', 'rongsheng.online', 'visible.true', '显示', 'content.mode.one', '单项')
,('rongsheng.book.drive', '试乘预约', 'Drive', '', 'rongsheng.book', 'visible.true', '显示', 'content.mode.one', '单项')
,('rongsheng.book.repair', '维修预约', 'Repair', '', 'rongsheng.book', 'visible.true', '显示', 'content.mode.one', '单项')
,('rongsheng.book.maintain', '保养预约', 'Maintain', '', 'rongsheng.book', 'visible.true', '显示', 'content.mode.one', '单项')
,('rongsheng.book.buy', '订车预约', 'Buy', '', 'rongsheng.book', 'visible.true', '显示', 'content.mode.one', '单项')
;