INSERT INTO web_content(id, name, english, path, hasShow, hasShowName, mode, modeName) 
VALUES
('ruihe', '吉林市瑞合汽车贸易有限公司', 'JiLin LongFu', '', 'visible.true', '显示', 'content.mode.one', '单项');

INSERT INTO web_content(id, name, english, path, parentId, hasShow, hasShowName, mode, modeName) 
VALUES

 ('ruihe.home', '首页', 'Home', 'index.jsp', 'ruihe', 'visible.true', '显示', 'content.mode.one', '单项')
,('ruihe.about', '企业介绍', 'About', '', 'ruihe', 'visible.true', '显示', 'content.mode.one', '单项')
,('ruihe.new', '新闻中心', 'New', '', 'ruihe', 'visible.true', '显示', 'content.mode.more', '多项')
,('ruihe.sall', '销售服务', 'Sall', '', 'ruihe', 'visible.true', '显示', 'content.mode.one', '单项')
,('ruihe.salled', '售后服务', 'Salled', '', 'ruihe', 'visible.true', '显示', 'content.mode.one', '单项')
,('ruihe.insurance', '保险服务', 'Insurance', '', 'ruihe', 'visible.true', '显示', 'content.mode.one', '单项')
,('ruihe.online', '在线客服', 'Online', '', 'ruihe', 'visible.true', '显示', 'content.mode.one', '单项')
,('ruihe.book', '预约服务', 'Book', '', 'ruihe', 'visible.true', '显示', 'content.mode.one', '单项')
,('ruihe.about.introduce', '企业介绍', 'Introduce', '', 'ruihe.about', 'visible.true', '显示', 'content.mode.one', '单项')
,('ruihe.about.glory', '公司荣誉', 'Glory', '', 'ruihe.about', 'visible.true', '显示', 'content.mode.one', '单项')
,('ruihe.about.form', '公司形象', 'Form', '', 'ruihe.about', 'visible.true', '显示', 'content.mode.one', '单项')
,('ruihe.about.contact', '联系方式', 'Contact', '', 'ruihe.about', 'visible.true', '显示', 'content.mode.one', '单项')
,('ruihe.new.offsall', '优惠活动', 'OffSall', '', 'ruihe.new', 'visible.true', '显示', 'content.mode.more', '多项')
,('ruihe.new.company', '公司新闻', 'Company', '', 'ruihe.new', 'visible.true', '显示', 'content.mode.more', '多项')
,('ruihe.new.car', '行业新闻', 'Car', '', 'ruihe.new', 'visible.true', '显示', 'content.mode.more', '多项')
,('ruihe.sall.new', '新车报价', 'NewCar', '', 'ruihe.sall', 'visible.true', '显示', 'content.mode.one', '单项')
,('ruihe.sall.offsall', '优惠促销', 'OffSall', '', 'ruihe.sall', 'visible.true', '显示', 'content.mode.one', '单项')
,('ruihe.sall.special', '特色服务', 'Special', '', 'ruihe.sall', 'visible.true', '显示', 'content.mode.one', '单项')
,('ruihe.salled.notice', '公告', 'Notice', '', 'ruihe.salled', 'visible.true', '显示', 'content.mode.one', '单项')
,('ruihe.salled.repair', '保修保养服务', 'Repair', '', 'ruihe.salled', 'visible.true', '显示', 'content.mode.one', '单项')
,('ruihe.salled.special', '特色服务', 'Special', '', 'ruihe.salled', 'visible.true', '显示', 'content.mode.one', '单项')
,('ruihe.salled.help', '服务手册', 'Help', '', 'ruihe.salled', 'visible.true', '显示', 'content.mode.one', '单项')
,('ruihe.insurance.introduce', '保险服务介绍', 'Introduce', '', 'ruihe.insurance', 'visible.true', '显示', 'content.mode.one', '单项')
,('ruihe.insurance.knowledge', '保险知识', 'Knowledge', '', 'ruihe.insurance', 'visible.true', '显示', 'content.mode.one', '单项')
,('ruihe.insurance.indemnify', '保险理赔', 'Insurance', '', 'ruihe.insurance', 'visible.true', '显示', 'content.mode.one', '单项')
,('ruihe.online.enquire', '资讯客服', 'Enquire', '', 'ruihe.online', 'visible.true', '显示', 'content.mode.one', '单项')
,('ruihe.online.complain', '投诉意见', 'Complain', 'cus_advise.jsp', 'ruihe.online', 'visible.true', '显示', 'content.mode.one', '单项')
,('ruihe.online.message', '客户留言', 'Message', 'cus_message.jsp', 'ruihe.online', 'visible.true', '显示', 'content.mode.one', '单项')
,('ruihe.book.drive', '试乘预约', 'Drive', '', 'ruihe.book', 'visible.true', '显示', 'content.mode.one', '单项')
,('ruihe.book.repair', '维修预约', 'Repair', '', 'ruihe.book', 'visible.true', '显示', 'content.mode.one', '单项')
,('ruihe.book.maintain', '保养预约', 'Maintain', '', 'ruihe.book', 'visible.true', '显示', 'content.mode.one', '单项')
,('ruihe.book.buy', '订车预约', 'Buy', '', 'ruihe.book', 'visible.true', '显示', 'content.mode.one', '单项')
;