INSERT INTO web_content(id, name, english, path, hasShow, hasShowName, mode, modeName) 
VALUES
('suixin', '绥化融展绥鑫专营店', 'JiLin LongFu', '', 'visible.true', '显示', 'content.mode.one', '单项');

INSERT INTO web_content(id, name, english, path, parentId, hasShow, hasShowName, mode, modeName) 
VALUES

 ('suixin.home', '首页', 'Home', 'index.jsp', 'suixin', 'visible.true', '显示', 'content.mode.one', '单项')
,('suixin.about', '企业介绍', 'About', '', 'suixin', 'visible.true', '显示', 'content.mode.one', '单项')
,('suixin.new', '新闻中心', 'New', '', 'suixin', 'visible.true', '显示', 'content.mode.more', '多项')
,('suixin.sall', '销售服务', 'Sall', '', 'suixin', 'visible.true', '显示', 'content.mode.one', '单项')
,('suixin.salled', '售后服务', 'Salled', '', 'suixin', 'visible.true', '显示', 'content.mode.one', '单项')
,('suixin.insurance', '保险服务', 'Insurance', '', 'suixin', 'visible.true', '显示', 'content.mode.one', '单项')
,('suixin.online', '在线客服', 'Online', '', 'suixin', 'visible.true', '显示', 'content.mode.one', '单项')
,('suixin.book', '预约服务', 'Book', '', 'suixin', 'visible.true', '显示', 'content.mode.one', '单项')
,('suixin.about.introduce', '企业介绍', 'Introduce', '', 'suixin.about', 'visible.true', '显示', 'content.mode.one', '单项')
,('suixin.about.glory', '公司荣誉', 'Glory', '', 'suixin.about', 'visible.true', '显示', 'content.mode.one', '单项')
,('suixin.about.form', '公司形象', 'Form', '', 'suixin.about', 'visible.true', '显示', 'content.mode.one', '单项')
,('suixin.about.contact', '联系方式', 'Contact', '', 'suixin.about', 'visible.true', '显示', 'content.mode.one', '单项')
,('suixin.new.offsall', '优惠活动', 'OffSall', '', 'suixin.new', 'visible.true', '显示', 'content.mode.more', '多项')
,('suixin.new.company', '公司新闻', 'Company', '', 'suixin.new', 'visible.true', '显示', 'content.mode.more', '多项')
,('suixin.new.car', '行业新闻', 'Car', '', 'suixin.new', 'visible.true', '显示', 'content.mode.more', '多项')
,('suixin.sall.new', '新车报价', 'NewCar', '', 'suixin.sall', 'visible.true', '显示', 'content.mode.one', '单项')
,('suixin.sall.offsall', '优惠促销', 'OffSall', '', 'suixin.sall', 'visible.true', '显示', 'content.mode.one', '单项')
,('suixin.sall.special', '特色服务', 'Special', '', 'suixin.sall', 'visible.true', '显示', 'content.mode.one', '单项')
,('suixin.salled.notice', '公告', 'Notice', '', 'suixin.salled', 'visible.true', '显示', 'content.mode.one', '单项')
,('suixin.salled.repair', '保修保养服务', 'Repair', '', 'suixin.salled', 'visible.true', '显示', 'content.mode.one', '单项')
,('suixin.salled.special', '特色服务', 'Special', '', 'suixin.salled', 'visible.true', '显示', 'content.mode.one', '单项')
,('suixin.salled.help', '服务手册', 'Help', '', 'suixin.salled', 'visible.true', '显示', 'content.mode.one', '单项')
,('suixin.insurance.introduce', '保险服务介绍', 'Introduce', '', 'suixin.insurance', 'visible.true', '显示', 'content.mode.one', '单项')
,('suixin.insurance.knowledge', '保险知识', 'Knowledge', '', 'suixin.insurance', 'visible.true', '显示', 'content.mode.one', '单项')
,('suixin.insurance.indemnify', '保险理赔', 'Insurance', '', 'suixin.insurance', 'visible.true', '显示', 'content.mode.one', '单项')
,('suixin.online.enquire', '资讯客服', 'Enquire', '', 'suixin.online', 'visible.true', '显示', 'content.mode.one', '单项')
,('suixin.online.complain', '投诉意见', 'Complain', 'cus_advise.jsp', 'suixin.online', 'visible.true', '显示', 'content.mode.one', '单项')
,('suixin.online.message', '客户留言', 'Message', 'cus_message.jsp', 'suixin.online', 'visible.true', '显示', 'content.mode.one', '单项')
,('suixin.book.drive', '试乘预约', 'Drive', '', 'suixin.book', 'visible.true', '显示', 'content.mode.one', '单项')
,('suixin.book.repair', '维修预约', 'Repair', '', 'suixin.book', 'visible.true', '显示', 'content.mode.one', '单项')
,('suixin.book.maintain', '保养预约', 'Maintain', '', 'suixin.book', 'visible.true', '显示', 'content.mode.one', '单项')
,('suixin.book.buy', '订车预约', 'Buy', '', 'suixin.book', 'visible.true', '显示', 'content.mode.one', '单项')
;