INSERT INTO web_content(id, name, english, path, hasShow, hasShowName, mode, modeName) 
VALUES
('xingbang', '哈尔滨融展兴邦专营店', 'JiLin LongFu', '', 'visible.true', '显示', 'content.mode.one', '单项');

INSERT INTO web_content(id, name, english, path, parentId, hasShow, hasShowName, mode, modeName) 
VALUES

 ('xingbang.home', '首页', 'Home', 'index.jsp', 'xingbang', 'visible.true', '显示', 'content.mode.one', '单项')
,('xingbang.about', '企业介绍', 'About', '', 'xingbang', 'visible.true', '显示', 'content.mode.one', '单项')
,('xingbang.new', '新闻中心', 'New', '', 'xingbang', 'visible.true', '显示', 'content.mode.more', '多项')
,('xingbang.sall', '销售服务', 'Sall', '', 'xingbang', 'visible.true', '显示', 'content.mode.one', '单项')
,('xingbang.salled', '售后服务', 'Salled', '', 'xingbang', 'visible.true', '显示', 'content.mode.one', '单项')
,('xingbang.insurance', '保险服务', 'Insurance', '', 'xingbang', 'visible.true', '显示', 'content.mode.one', '单项')
,('xingbang.online', '在线客服', 'Online', '', 'xingbang', 'visible.true', '显示', 'content.mode.one', '单项')
,('xingbang.book', '预约服务', 'Book', '', 'xingbang', 'visible.true', '显示', 'content.mode.one', '单项')
,('xingbang.about.introduce', '企业介绍', 'Introduce', '', 'xingbang.about', 'visible.true', '显示', 'content.mode.one', '单项')
,('xingbang.about.glory', '公司荣誉', 'Glory', '', 'xingbang.about', 'visible.true', '显示', 'content.mode.one', '单项')
,('xingbang.about.form', '公司形象', 'Form', '', 'xingbang.about', 'visible.true', '显示', 'content.mode.one', '单项')
,('xingbang.about.contact', '联系方式', 'Contact', '', 'xingbang.about', 'visible.true', '显示', 'content.mode.one', '单项')
,('xingbang.new.offsall', '优惠活动', 'OffSall', '', 'xingbang.new', 'visible.true', '显示', 'content.mode.more', '多项')
,('xingbang.new.company', '公司新闻', 'Company', '', 'xingbang.new', 'visible.true', '显示', 'content.mode.more', '多项')
,('xingbang.new.car', '行业新闻', 'Car', '', 'xingbang.new', 'visible.true', '显示', 'content.mode.more', '多项')
,('xingbang.sall.new', '新车报价', 'NewCar', '', 'xingbang.sall', 'visible.true', '显示', 'content.mode.one', '单项')
,('xingbang.sall.offsall', '优惠促销', 'OffSall', '', 'xingbang.sall', 'visible.true', '显示', 'content.mode.one', '单项')
,('xingbang.sall.special', '特色服务', 'Special', '', 'xingbang.sall', 'visible.true', '显示', 'content.mode.one', '单项')
,('xingbang.salled.notice', '公告', 'Notice', '', 'xingbang.salled', 'visible.true', '显示', 'content.mode.one', '单项')
,('xingbang.salled.repair', '保修保养服务', 'Repair', '', 'xingbang.salled', 'visible.true', '显示', 'content.mode.one', '单项')
,('xingbang.salled.special', '特色服务', 'Special', '', 'xingbang.salled', 'visible.true', '显示', 'content.mode.one', '单项')
,('xingbang.salled.help', '服务手册', 'Help', '', 'xingbang.salled', 'visible.true', '显示', 'content.mode.one', '单项')
,('xingbang.insurance.introduce', '保险服务介绍', 'Introduce', '', 'xingbang.insurance', 'visible.true', '显示', 'content.mode.one', '单项')
,('xingbang.insurance.knowledge', '保险知识', 'Knowledge', '', 'xingbang.insurance', 'visible.true', '显示', 'content.mode.one', '单项')
,('xingbang.insurance.indemnify', '保险理赔', 'Insurance', '', 'xingbang.insurance', 'visible.true', '显示', 'content.mode.one', '单项')
,('xingbang.online.enquire', '资讯客服', 'Enquire', '', 'xingbang.online', 'visible.true', '显示', 'content.mode.one', '单项')
,('xingbang.online.complain', '投诉意见', 'Complain', 'cus_advise.jsp', 'xingbang.online', 'visible.true', '显示', 'content.mode.one', '单项')
,('xingbang.online.message', '客户留言', 'Message', 'cus_message.jsp', 'xingbang.online', 'visible.true', '显示', 'content.mode.one', '单项')
,('xingbang.book.drive', '试乘预约', 'Drive', '', 'xingbang.book', 'visible.true', '显示', 'content.mode.one', '单项')
,('xingbang.book.repair', '维修预约', 'Repair', '', 'xingbang.book', 'visible.true', '显示', 'content.mode.one', '单项')
,('xingbang.book.maintain', '保养预约', 'Maintain', '', 'xingbang.book', 'visible.true', '显示', 'content.mode.one', '单项')
,('xingbang.book.buy', '订车预约', 'Buy', '', 'xingbang.book', 'visible.true', '显示', 'content.mode.one', '单项')
;