<?xml version="1.0" encoding="UTF-8"?>
<saturn-action>
	<information id="0" next="" x="0" y="0">
		<key>/carModule/action/QueryCarDetailInfo.action</key>
		<name>查询车辆档案详细</name>
		<description>查询车辆档案详细</description>
	</information>
	<view id="5" next="" x="656" y="258">
		<name>editcar</name>
		<type>jsp</type>
		<location>/crm/carModule/web/editcar.jsp</location>
		<description></description>
	</view>
	<view id="3" next="" x="660" y="111">
		<name>cardetail</name>
		<type>jsp</type>
		<location>/crm/carModule/web/cardetail.jsp</location>
		<description></description>
	</view>
	<decision next="" id="4" x="412" y="170">
		<name>选择1</name>
		<if then="3" else="5">
			<expr>type eq 'detail'</expr>
		</if>
		<parameters></parameters>
		<description></description>
	</decision>
	<start id="1" next="7" x="81" y="161">
		<name>开始</name>
		<transaction autorollback="false"></transaction>
		<parameters></parameters>
		<description></description>
	</start>
	<logic exception="" id="7" next="4" x="226" y="284">
		<key>crm::/carModule/logic/QueryCarDetailInfo.logic</key>
		<name>查询车辆档案详细</name>
		<transaction type="supports"></transaction>
		<parameters>
			<parameter id="1" name="primarykeyvalue" classType="java.lang.String" passingType="in">
				<value-key>carid</value-key>
				<scope>2</scope>
				<description>主键值</description>
			</parameter>
			<parameter id="2" name="customerid" classType="java.lang.String" passingType="in">
				<value-key>customerid</value-key>
				<scope>2</scope>
				<description>返回SaturnData</description>
			</parameter>
			<parameter id="3" name="result" classType="edu.ccut.saturn.component.SaturnData" passingType="out">
				<value-key>cstmData</value-key>
				<scope>2</scope>
				<description>返回SaturnData</description>
			</parameter>
			<parameter id="4" name="result" classType="edu.ccut.saturn.component.SaturnData" passingType="out">
				<value-key>carData</value-key>
				<scope>2</scope>
				<description>返回SaturnData</description>
			</parameter>
			<parameter id="5" name="saturnData" classType="edu.ccut.saturn.component.SaturnData" passingType="out">
				<value-key>pinyinlist</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
		</parameters>
		<description>查询车辆档案详细</description>
	</logic>
	<logic exception="" id="6" next="" x="230" y="164">
		<key>crm::/carModule/logic/QueryCarDetailInfo.logic</key>
		<name>查询车辆档案详细</name>
		<transaction type="supports"></transaction>
		<parameters>
			<parameter id="1" name="primarykeyvalue" classType="java.lang.String" passingType="in">
				<value-key>carid</value-key>
				<scope>2</scope>
				<description>主键值</description>
			</parameter>
			<parameter id="2" name="customerid" classType="java.lang.String" passingType="in">
				<value-key>customerid</value-key>
				<scope>2</scope>
				<description>返回SaturnData</description>
			</parameter>
			<parameter id="3" name="result" classType="edu.ccut.saturn.component.SaturnData" passingType="out">
				<value-key>cstmData</value-key>
				<scope>2</scope>
				<description>返回SaturnData</description>
			</parameter>
			<parameter id="4" name="result" classType="edu.ccut.saturn.component.SaturnData" passingType="out">
				<value-key>carData</value-key>
				<scope>2</scope>
				<description>返回SaturnData</description>
			</parameter>
		</parameters>
		<description>查询车辆档案详细</description>
	</logic>
	<connection source="1" target="7" style="1" name=""></connection>
	<connection source="4" target="3" style="1" name="未命名"></connection>
	<connection source="4" target="5" style="2" name="未命名"></connection>
	<connection source="7" target="4" style="1" name=""></connection>
</saturn-action>