INSERT INTO web_content(id, name, english, path, hasShow, hasShowName, mode, modeName) 
VALUES
('changchunruifu', '长春瑞孚汽车销售服务有限公司', 'ChangChun RuiFu', '', 'visible.true', '显示', 'content.mode.one', '单项');

INSERT INTO web_content(id, name, english, path, parentId, hasShow, hasShowName, mode, modeName) 
VALUES

 ('changchunruifu.home', '首页', 'Home', '', 'changchunruifu', 'visible.true', '显示', 'content.mode.one', '单项')
,('changchunruifu.about', '企业介绍', 'About', '', 'changchunruifu', 'visible.true', '显示', 'content.mode.one', '单项')
,('changchunruifu.new', '新闻中心', 'New', '', 'changchunruifu', 'visible.true', '显示', 'content.mode.more', '多项')
,('changchunruifu.sall', '销售服务', 'Sall', '', 'changchunruifu', 'visible.true', '显示', 'content.mode.one', '单项')
,('changchunruifu.salled', '售后服务', 'Salled', '', 'changchunruifu', 'visible.true', '显示', 'content.mode.one', '单项')
,('changchunruifu.insurance', '保险服务', 'Insurance', '', 'changchunruifu', 'visible.true', '显示', 'content.mode.one', '单项')
,('changchunruifu.online', '在线客服', 'Online', '', 'changchunruifu', 'visible.true', '显示', 'content.mode.one', '单项')
,('changchunruifu.book', '预约服务', 'Book', '', 'changchunruifu', 'visible.true', '显示', 'content.mode.one', '单项')
,('changchunruifu.about.introduce', '企业介绍', 'Introduce', '', 'changchunruifu.about', 'visible.true', '显示', 'content.mode.one', '单项')
,('changchunruifu.about.glory', '公司荣誉', 'Glory', '', 'changchunruifu.about', 'visible.true', '显示', 'content.mode.one', '单项')
,('changchunruifu.about.form', '公司形象', 'Form', '', 'changchunruifu.about', 'visible.true', '显示', 'content.mode.one', '单项')
,('changchunruifu.about.contact', '联系方式', 'Contact', '', 'changchunruifu.about', 'visible.true', '显示', 'content.mode.one', '单项')
,('changchunruifu.new.offsall', '优惠活动', 'OffSall', '', 'changchunruifu.new', 'visible.true', '显示', 'content.mode.more', '多项')
,('changchunruifu.new.company', '公司新闻', 'Company', '', 'changchunruifu.new', 'visible.true', '显示', 'content.mode.more', '多项')
,('changchunruifu.new.car', '行业新闻', 'Car', '', 'changchunruifu.new', 'visible.true', '显示', 'content.mode.more', '多项')
,('changchunruifu.sall.new', '新车报价', 'NewCar', '', 'changchunruifu.sall', 'visible.true', '显示', 'content.mode.one', '单项')
,('changchunruifu.sall.offsall', '优惠促销', 'OffSall', '', 'changchunruifu.sall', 'visible.true', '显示', 'content.mode.one', '单项')
,('changchunruifu.sall.special', '特色服务', 'Special', '', 'changchunruifu.sall', 'visible.true', '显示', 'content.mode.one', '单项')
,('changchunruifu.salled.notice', '公告', 'Notice', '', 'changchunruifu.salled', 'visible.true', '显示', 'content.mode.one', '单项')
,('changchunruifu.salled.repair', '保修保养服务', 'Repair', '', 'changchunruifu.salled', 'visible.true', '显示', 'content.mode.one', '单项')
,('changchunruifu.salled.special', '特色服务', 'Special', '', 'changchunruifu.salled', 'visible.true', '显示', 'content.mode.one', '单项')
,('changchunruifu.salled.help', '服务手册', 'Help', '', 'changchunruifu.salled', 'visible.true', '显示', 'content.mode.one', '单项')
,('changchunruifu.insurance.introduce', '保险服务介绍', 'Introduce', '', 'changchunruifu.insurance', 'visible.true', '显示', 'content.mode.one', '单项')
,('changchunruifu.insurance.knowledge', '保险知识', 'Knowledge', '', 'changchunruifu.insurance', 'visible.true', '显示', 'content.mode.one', '单项')
,('changchunruifu.insurance.indemnify', '保险理赔', 'Insurance', '', 'changchunruifu.insurance', 'visible.true', '显示', 'content.mode.one', '单项')
,('changchunruifu.online.enquire', '资讯客服', 'Enquire', '', 'changchunruifu.online', 'visible.true', '显示', 'content.mode.one', '单项')
,('changchunruifu.online.complain', '投诉意见', 'Complain', '', 'changchunruifu.online', 'visible.true', '显示', 'content.mode.one', '单项')
,('changchunruifu.online.message', '客户留言', 'Message', '', 'changchunruifu.online', 'visible.true', '显示', 'content.mode.one', '单项')
,('changchunruifu.book.drive', '试乘预约', 'Drive', '', 'changchunruifu.book', 'visible.true', '显示', 'content.mode.one', '单项')
,('changchunruifu.book.repair', '维修预约', 'Repair', '', 'changchunruifu.book', 'visible.true', '显示', 'content.mode.one', '单项')
,('changchunruifu.book.maintain', '保养预约', 'Maintain', '', 'changchunruifu.book', 'visible.true', '显示', 'content.mode.one', '单项')
,('changchunruifu.book.buy', '订车预约', 'Buy', '', 'changchunruifu.book', 'visible.true', '显示', 'content.mode.one', '单项')
;