INSERT INTO web_content(id, name, english, path, hasShow, hasShowName, mode, modeName) 
VALUES
('jilinshenglongfu', '吉林省隆孚汽车销售服务有限公司', 'JiLin LongFu', '', 'visible.true', '显示', 'content.mode.one', '单项');

INSERT INTO web_content(id, name, english, path, parentId, hasShow, hasShowName, mode, modeName) 
VALUES

 ('jilinshenglongfu.home', '首页', 'Home', '', 'jilinshenglongfu', 'visible.true', '显示', 'content.mode.one', '单项')
,('jilinshenglongfu.about', '企业介绍', 'About', '', 'jilinshenglongfu', 'visible.true', '显示', 'content.mode.one', '单项')
,('jilinshenglongfu.new', '新闻中心', 'New', '', 'jilinshenglongfu', 'visible.true', '显示', 'content.mode.more', '多项')
,('jilinshenglongfu.sall', '销售服务', 'Sall', '', 'jilinshenglongfu', 'visible.true', '显示', 'content.mode.one', '单项')
,('jilinshenglongfu.salled', '售后服务', 'Salled', '', 'jilinshenglongfu', 'visible.true', '显示', 'content.mode.one', '单项')
,('jilinshenglongfu.insurance', '保险服务', 'Insurance', '', 'jilinshenglongfu', 'visible.true', '显示', 'content.mode.one', '单项')
,('jilinshenglongfu.online', '在线客服', 'Online', '', 'jilinshenglongfu', 'visible.true', '显示', 'content.mode.one', '单项')
,('jilinshenglongfu.book', '预约服务', 'Book', '', 'jilinshenglongfu', 'visible.true', '显示', 'content.mode.one', '单项')
,('jilinshenglongfu.about.introduce', '企业介绍', 'Introduce', '', 'jilinshenglongfu.about', 'visible.true', '显示', 'content.mode.one', '单项')
,('jilinshenglongfu.about.glory', '公司荣誉', 'Glory', '', 'jilinshenglongfu.about', 'visible.true', '显示', 'content.mode.one', '单项')
,('jilinshenglongfu.about.form', '公司形象', 'Form', '', 'jilinshenglongfu.about', 'visible.true', '显示', 'content.mode.one', '单项')
,('jilinshenglongfu.about.contact', '联系方式', 'Contact', '', 'jilinshenglongfu.about', 'visible.true', '显示', 'content.mode.one', '单项')
,('jilinshenglongfu.new.offsall', '优惠活动', 'OffSall', '', 'jilinshenglongfu.new', 'visible.true', '显示', 'content.mode.more', '多项')
,('jilinshenglongfu.new.company', '公司新闻', 'Company', '', 'jilinshenglongfu.new', 'visible.true', '显示', 'content.mode.more', '多项')
,('jilinshenglongfu.new.car', '行业新闻', 'Car', '', 'jilinshenglongfu.new', 'visible.true', '显示', 'content.mode.more', '多项')
,('jilinshenglongfu.sall.new', '新车报价', 'NewCar', '', 'jilinshenglongfu.sall', 'visible.true', '显示', 'content.mode.one', '单项')
,('jilinshenglongfu.sall.offsall', '优惠促销', 'OffSall', '', 'jilinshenglongfu.sall', 'visible.true', '显示', 'content.mode.one', '单项')
,('jilinshenglongfu.sall.special', '特色服务', 'Special', '', 'jilinshenglongfu.sall', 'visible.true', '显示', 'content.mode.one', '单项')
,('jilinshenglongfu.salled.notice', '公告', 'Notice', '', 'jilinshenglongfu.salled', 'visible.true', '显示', 'content.mode.one', '单项')
,('jilinshenglongfu.salled.repair', '保修保养服务', 'Repair', '', 'jilinshenglongfu.salled', 'visible.true', '显示', 'content.mode.one', '单项')
,('jilinshenglongfu.salled.special', '特色服务', 'Special', '', 'jilinshenglongfu.salled', 'visible.true', '显示', 'content.mode.one', '单项')
,('jilinshenglongfu.salled.help', '服务手册', 'Help', '', 'jilinshenglongfu.salled', 'visible.true', '显示', 'content.mode.one', '单项')
,('jilinshenglongfu.insurance.introduce', '保险服务介绍', 'Introduce', '', 'jilinshenglongfu.insurance', 'visible.true', '显示', 'content.mode.one', '单项')
,('jilinshenglongfu.insurance.knowledge', '保险知识', 'Knowledge', '', 'jilinshenglongfu.insurance', 'visible.true', '显示', 'content.mode.one', '单项')
,('jilinshenglongfu.insurance.indemnify', '保险理赔', 'Insurance', '', 'jilinshenglongfu.insurance', 'visible.true', '显示', 'content.mode.one', '单项')
,('jilinshenglongfu.online.enquire', '资讯客服', 'Enquire', '', 'jilinshenglongfu.online', 'visible.true', '显示', 'content.mode.one', '单项')
,('jilinshenglongfu.online.complain', '投诉意见', 'Complain', '', 'jilinshenglongfu.online', 'visible.true', '显示', 'content.mode.one', '单项')
,('jilinshenglongfu.online.message', '客户留言', 'Message', '', 'jilinshenglongfu.online', 'visible.true', '显示', 'content.mode.one', '单项')
,('jilinshenglongfu.book.drive', '试乘预约', 'Drive', '', 'jilinshenglongfu.book', 'visible.true', '显示', 'content.mode.one', '单项')
,('jilinshenglongfu.book.repair', '维修预约', 'Repair', '', 'jilinshenglongfu.book', 'visible.true', '显示', 'content.mode.one', '单项')
,('jilinshenglongfu.book.maintain', '保养预约', 'Maintain', '', 'jilinshenglongfu.book', 'visible.true', '显示', 'content.mode.one', '单项')
,('jilinshenglongfu.book.buy', '订车预约', 'Buy', '', 'jilinshenglongfu.book', 'visible.true', '显示', 'content.mode.one', '单项')
;