<?xml version="1.0" encoding="UTF-8"?>
<saturn-action>
	<information id="0" next="" x="0" y="0">
		<key>/dutyModule/action/DutyReportAll.action</key>
		<name>总值综合报</name>
		<description></description>
	</information>
	<view id="5" next="" x="528" y="379">
		<name>dutyreportallexcel</name>
		<type>jsp</type>
		<location>/crm/dutyModule/web/dutyreportallexcel.jsp</location>
		<description></description>
	</view>
	<view id="2" next="" x="505" y="181">
		<name>dutyreportall</name>
		<type>jsp</type>
		<location>/crm/dutyModule/web/dutyreportall.jsp</location>
		<description></description>
	</view>
	<connection source="3" target="4" style="1" name=""></connection>
	<start id="1" next="6" x="81" y="161">
		<name>开始</name>
		<transaction autorollback="false"></transaction>
		<parameters></parameters>
		<description></description>
	</start>
	<decision next="" id="4" x="430" y="275">
		<name>'excel'==op</name>
		<if then="5" else="2">
			<expr>'excel'==op</expr>
		</if>
		<parameters></parameters>
		<description></description>
	</decision>
	<logic exception="" id="6" next="4" x="247" y="233">
		<key>crm::/dutyModule/logic/DutyReportAll.logic</key>
		<name>总值综合报</name>
		<transaction type="supports"></transaction>
		<parameters>
			<parameter id="1" name="result" classType="java.util.ArrayList" passingType="out">
				<value-key>allresult</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="2" name="dutyintime" classType="java.lang.String" passingType="in">
				<value-key>min_dutyintime</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="3" name="" classType="java.lang.String" passingType="in">
				<value-key>max_dutyintime</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="4" name="" classType="java.lang.String" passingType="in">
				<value-key>min_dutypredelivtime</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="5" name="" classType="java.lang.String" passingType="in">
				<value-key>max_dutypredelivtime</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="6" name="" classType="java.lang.String" passingType="in">
				<value-key>dutystaff</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
		</parameters>
		<description></description>
	</logic>
	<connection source="1" target="6" style="1" name=""></connection>
	<connection source="6" target="4" style="1" name=""></connection>
	<connection source="4" target="2" style="2" name="未命名"></connection>
	<connection source="4" target="5" style="1" name="未命名"></connection>
</saturn-action>