<?xml version="1.0" encoding="UTF-8"?>
<saturn-action>
	<information id="0" next="" x="0" y="0">
		<key>/ccioModule/action/DelIODataById.action</key>
		<name>DelIODataById</name>
		<description></description>
	</information>
	<start id="1" next="4" x="81" y="161">
		<name>开始</name>
		<transaction autorollback="false"></transaction>
		<parameters></parameters>
		<description></description>
	</start>
	<decision next="" id="4" x="224" y="149">
		<name>i_id!=null&amp;&amp;i_id.trim()!=&quot;&quot;</name>
		<if then="2" else="3">
			<expr>i_id!=null&amp;&amp;i_id.trim()!=&quot;&quot;</expr>
		</if>
		<parameters></parameters>
		<description></description>
	</decision>
	<action id="3" next="" x="456" y="162">
		<key>crm::/ccioModule/action/GetIodateList.action</key>
		<name>获得到店离店时间列表</name>
		<parameters></parameters>
		<description></description>
	</action>
	<logic exception="" id="2" next="3" x="251" y="280">
		<key>crm::/ccioModule/logic/DelIODataById.logic</key>
		<name>DelIODataById</name>
		<transaction type="supports"></transaction>
		<parameters>
			<parameter id="1" name="primarykeyValue" classType="java.lang.String" passingType="in">
				<value-key>i_id</value-key>
				<scope>2</scope>
				<description>primarykey</description>
			</parameter>
		</parameters>
		<description></description>
	</logic>
	<connection source="1" target="4" style="1" name=""></connection>
	<connection source="2" target="3" style="1" name=""></connection>
	<connection source="4" target="2" style="1" name="未命名"></connection>
	<connection source="4" target="3" style="2" name="未命名"></connection>
</saturn-action>