<?xml version="1.0" encoding="UTF-8"?>
<saturn-action>
	<information id="0" next="" x="0" y="0">
		<key>/ccioModule/action/GetCardToVB.action</key>
		<name>下载到写卡客户端</name>
		<description></description>
	</information>
	<start id="1" next="2" x="81" y="161">
		<name>开始</name>
		<transaction autorollback="false"></transaction>
		<parameters></parameters>
		<description></description>
	</start>
	<view id="5" next="" x="367" y="288">
		<name>cardtovb</name>
		<type>jsp</type>
		<location>/crm/ccioModule/web/cardtovb.jsp</location>
		<description></description>
	</view>
	<transform id="3" next="4" x="354" y="164">
		<value-key>cardresult</value-key>
		<type>json</type>
		<name>转移4</name>
		<contents>
			<content id="1" type="list">
				<content-value-key>cardresult</content-value-key>
			</content>
		</contents>
		<description></description>
	</transform>
	<view id="4" next="" x="453" y="165">
		<name>视图7</name>
		<type>json</type>
		<location>cardresult</location>
		<description></description>
	</view>
	<logic exception="" id="2" next="5" x="228" y="157">
		<key>crm::/ccioModule/logic/GetCardToVB.logic</key>
		<name>下载到写卡客户端</name>
		<transaction type="supports"></transaction>
		<parameters>
			<parameter id="1" name="result" classType="java.util.ArrayList" passingType="out">
				<value-key>cardresult</value-key>
				<scope>2</scope>
				<description>返回SaturnData结果集</description>
			</parameter>
		</parameters>
		<description></description>
	</logic>
	<connection source="1" target="2" style="1" name=""></connection>
	<connection source="2" target="5" style="1" name=""></connection>
	<connection source="3" target="4" style="1" name=""></connection>
</saturn-action>