<?xml version="1.0" encoding="UTF-8"?>
<saturn-action>
	<information id="0" next="" x="0" y="0">
		<key>/ccioModule/action/SetCard.action</key>
		<name>新增卡</name>
		<description></description>
	</information>
	<logic exception="" id="4" next="5" x="347" y="118">
		<key>crm::/ccioModule/logic/GetDictById.logic</key>
		<name>按ID获得基础信息</name>
		<transaction type="supports"></transaction>
		<parameters>
			<parameter id="1" name="result" classType="edu.ccut.saturn.component.SaturnData" passingType="out">
				<value-key>c_result</value-key>
				<scope>1</scope>
				<description>返回SaturnData</description>
			</parameter>
			<parameter id="2" name="primarykeyvalue" classType="java.lang.String" passingType="in">
				<value-key>c_c</value-key>
				<scope>2</scope>
				<description>主键值</description>
			</parameter>
		</parameters>
		<description></description>
	</logic>
	<logic exception="" id="5" next="6" x="394" y="248">
		<key>crm::/ccioModule/logic/GetDictById.logic</key>
		<name>按ID获得基础信息</name>
		<transaction type="supports"></transaction>
		<parameters>
			<parameter id="1" name="result" classType="edu.ccut.saturn.component.SaturnData" passingType="out">
				<value-key>d_result</value-key>
				<scope>1</scope>
				<description>返回SaturnData</description>
			</parameter>
			<parameter id="2" name="primarykeyvalue" classType="java.lang.String" passingType="in">
				<value-key>c_d</value-key>
				<scope>2</scope>
				<description>主键值</description>
			</parameter>
		</parameters>
		<description></description>
	</logic>
	<logic exception="" id="6" next="9" x="460" y="120">
		<key>crm::/ccioModule/logic/SetCard.logic</key>
		<name>添加卡号</name>
		<transaction type="supports"></transaction>
		<parameters>
			<parameter id="1" name="fieldValue" classType="java.lang.String" passingType="in">
				<value-key>c_a</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="2" name="value" classType="java.lang.String" passingType="in">
				<value-key>c_b</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="3" name="value" classType="java.lang.String" passingType="in">
				<value-key>c_c</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="4" name="value" classType="java.lang.String" passingType="in">
				<value-key>c_d</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="5" name="c_a_v" classType="java.lang.String" passingType="in">
				<value-key>${a_result.d_value}</value-key>
				<scope>1</scope>
				<description>国家</description>
			</parameter>
			<parameter id="6" name="c_b_v" classType="java.lang.String" passingType="in">
				<value-key>${b_result.d_value}</value-key>
				<scope>1</scope>
				<description>省份</description>
			</parameter>
			<parameter id="7" name="c_c_v" classType="java.lang.String" passingType="in">
				<value-key>${c_result.d_value}</value-key>
				<scope>1</scope>
				<description>城市</description>
			</parameter>
			<parameter id="8" name="c_d_v" classType="java.lang.String" passingType="in">
				<value-key>${d_result.d_value}</value-key>
				<scope>1</scope>
				<description>4s店</description>
			</parameter>
			<parameter id="9" name="c_num" classType="java.lang.String" passingType="in">
				<value-key>c_num</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
		</parameters>
		<description></description>
	</logic>
	<logic exception="" id="2" next="3" x="227" y="121">
		<key>crm::/ccioModule/logic/GetDictById.logic</key>
		<name>按ID获得基础信息</name>
		<transaction type="supports"></transaction>
		<parameters>
			<parameter id="1" name="result" classType="edu.ccut.saturn.component.SaturnData" passingType="out">
				<value-key>a_result</value-key>
				<scope>1</scope>
				<description>返回SaturnData</description>
			</parameter>
			<parameter id="2" name="primarykeyvalue" classType="java.lang.String" passingType="in">
				<value-key>c_a</value-key>
				<scope>2</scope>
				<description>主键值</description>
			</parameter>
		</parameters>
		<description></description>
	</logic>
	<start id="1" next="8" x="86" y="214">
		<name>开始</name>
		<transaction autorollback="false"></transaction>
		<parameters></parameters>
		<description></description>
	</start>
	<view id="7" next="" x="657" y="252">
		<name>addcard</name>
		<type>jsp</type>
		<location>/crm/ccioModule/web/addcard.jsp</location>
		<description></description>
	</view>
	<logic exception="" id="3" next="4" x="275" y="252">
		<key>crm::/ccioModule/logic/GetDictById.logic</key>
		<name>按ID获得基础信息</name>
		<transaction type="supports"></transaction>
		<parameters>
			<parameter id="1" name="result" classType="edu.ccut.saturn.component.SaturnData" passingType="out">
				<value-key>b_result</value-key>
				<scope>1</scope>
				<description>返回SaturnData</description>
			</parameter>
			<parameter id="2" name="primarykeyvalue" classType="java.lang.String" passingType="in">
				<value-key>c_b</value-key>
				<scope>2</scope>
				<description>主键值</description>
			</parameter>
		</parameters>
		<description></description>
	</logic>
	<decision next="" id="8" x="176" y="361">
		<name>是否生成号</name>
		<if then="2" else="9">
			<expr>op=='creatz'</expr>
		</if>
		<parameters></parameters>
		<description></description>
	</decision>
	<action id="9" next="" x="531" y="362">
		<key>crm::/ccioModule/action/GetCardList.action</key>
		<name>获得卡号列表</name>
		<parameters></parameters>
		<description></description>
	</action>
	<connection source="1" target="8" style="1" name=""></connection>
	<connection source="3" target="4" style="1" name=""></connection>
	<connection source="2" target="3" style="1" name=""></connection>
	<connection source="4" target="5" style="1" name=""></connection>
	<connection source="5" target="6" style="1" name=""></connection>
	<connection source="6" target="9" style="1" name=""></connection>
	<connection source="8" target="2" style="1" name="未命名"></connection>
	<connection source="8" target="9" style="2" name="未命名"></connection>
</saturn-action>