<?xml version="1.0" encoding="UTF-8"?>
<saturn-action>
	<information id="0" next="" x="0" y="0">
		<key>/importModule/action/InsertService.action</key>
		<name>导入维修数据</name>
		<description>导入维修数据</description>
	</information>
	<start id="1" next="3" x="81" y="161">
		<name>开始</name>
		<transaction autorollback="false"></transaction>
		<parameters></parameters>
		<description></description>
	</start>
	<connection source="5" target="6" style="1" name=""></connection>
	<connection source="6" target="7" style="1" name=""></connection>
	<logic exception="" id="3" next="4" x="205" y="169">
		<key>crm::/importModule/logic/UploadExcel.logic</key>
		<name>UploadExcel</name>
		<transaction type="supports"></transaction>
		<parameters>
			<parameter id="1" name="file" classType="java.lang.Object" passingType="in">
				<value-key>excelFile</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="2" name="saveType" classType="java.lang.String" passingType="in">
				<value-key>'service'</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="3" name="" classType="java.lang.String" passingType="out">
				<value-key>filePath</value-key>
				<scope>1</scope>
				<description></description>
			</parameter>
		</parameters>
		<description></description>
	</logic>
	<action id="12" next="" x="572" y="204">
		<key>crm::/importModule/action/QueryImportResult.action</key>
		<name>查询导入结果</name>
		<parameters></parameters>
		<description>查询导入结果</description>
	</action>
	<logic exception="" id="8" next="" x="417" y="43">
		<key>crm::/importModule/logic/InsertServiceAll.logic</key>
		<name>导入维修数据</name>
		<transaction type="supports"></transaction>
		<parameters>
			<parameter id="1" name="importType" classType="java.lang.String" passingType="in">
				<value-key>'service'</value-key>
				<scope>1</scope>
				<description></description>
			</parameter>
			<parameter id="2" name="filePath" classType="java.lang.String" passingType="in">
				<value-key>filePath</value-key>
				<scope>1</scope>
				<description></description>
			</parameter>
			<parameter id="3" name="fieldValue" classType="java.lang.String" passingType="out">
				<value-key>importdate</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="4" name="fieldValue" classType="java.lang.String" passingType="in">
				<value-key>importtarget</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
		</parameters>
		<description>导入维修数据</description>
	</logic>
	<logic exception="" id="11" next="12" x="505" y="106">
		<key>crm::/importModule/logic/InsertImportData.logic</key>
		<name>插入导入信息记录</name>
		<transaction type="supports"></transaction>
		<parameters>
			<parameter id="1" name="fullkey" classType="java.lang.String" passingType="in">
				<value-key>'http://crm/coreModule/data::crm_service'</value-key>
				<scope>1</scope>
				<description>生成SaturnData所需的Fullkey</description>
			</parameter>
			<parameter id="2" name="" classType="java.lang.String" passingType="in">
				<value-key>importdate</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="3" name="fieldValue" classType="java.lang.String" passingType="in">
				<value-key>importtarget</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="4" name="" classType="java.lang.String" passingType="in">
				<value-key>importoper</value-key>
				<scope>1</scope>
				<description></description>
			</parameter>
		</parameters>
		<description>插入导入信息记录</description>
	</logic>
	<decision next="" id="4" x="242" y="286">
		<name>选择11</name>
		<if then="10" else="13">
			<expr>filePath==null</expr>
		</if>
		<parameters></parameters>
		<description></description>
	</decision>
	<view id="10" next="" x="264" y="379">
		<name>error</name>
		<type>jsp</type>
		<location>/crm/importModule/web/error.jsp</location>
		<description></description>
	</view>
	<view id="15" next="" x="463" y="369">
		<name>errornew</name>
		<type>jsp</type>
		<location>/crm/importModule/web/errornew.jsp</location>
		<description></description>
	</view>
	<decision next="" id="14" x="404" y="201">
		<name>选择6</name>
		<if then="11" else="15">
			<expr>result == &quot;success&quot;</expr>
		</if>
		<parameters></parameters>
		<description></description>
	</decision>
	<logic exception="" id="13" next="14" x="328" y="68">
		<key>crm::/importModule/logic/InsertServiceAll.logic</key>
		<name>导入维修数据</name>
		<transaction type="supports"></transaction>
		<parameters>
			<parameter id="1" name="importType" classType="java.lang.String" passingType="in">
				<value-key>'service'</value-key>
				<scope>1</scope>
				<description></description>
			</parameter>
			<parameter id="2" name="filePath" classType="java.lang.String" passingType="in">
				<value-key>filePath</value-key>
				<scope>1</scope>
				<description></description>
			</parameter>
			<parameter id="3" name="fieldValue" classType="java.lang.String" passingType="out">
				<value-key>importdate</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="4" name="fieldValue" classType="java.lang.String" passingType="in">
				<value-key>importtarget</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="5" name="result" classType="java.lang.String" passingType="out">
				<value-key>result</value-key>
				<scope>1</scope>
				<description></description>
			</parameter>
		</parameters>
		<description>导入维修数据</description>
	</logic>
	<connection source="1" target="3" style="1" name=""></connection>
	<connection source="3" target="4" style="1" name=""></connection>
	<connection source="11" target="12" style="1" name=""></connection>
	<connection source="4" target="10" style="1" name="未命名"></connection>
	<connection source="4" target="13" style="2" name="未命名"></connection>
	<connection source="13" target="14" style="1" name=""></connection>
	<connection source="14" target="15" style="2" name="未命名"></connection>
	<connection source="14" target="11" style="1" name="未命名"></connection>
</saturn-action>