<?xml version="1.0" encoding="UTF-8"?>
<saturn-action>
	<information id="0" next="" x="0" y="0">
		<key>/dutyModule/action/QueryDutyItemList.action</key>
		<name>获得详细列表</name>
		<description></description>
	</information>
	<view id="4" next="" x="537" y="231">
		<name>视图4</name>
		<type>json</type>
		<location>duty_item_result</location>
		<description></description>
	</view>
	<transform id="3" next="4" x="399" y="202">
		<value-key>duty_item_result</value-key>
		<type>json</type>
		<name>duty_item_result</name>
		<contents>
			<content id="1" type="list">
				<content-value-key>duty_item_result</content-value-key>
			</content>
		</contents>
		<description></description>
	</transform>
	<start id="1" next="2" x="81" y="161">
		<name>开始</name>
		<transaction autorollback="false"></transaction>
		<parameters></parameters>
		<description></description>
	</start>
	<logic exception="" id="2" next="3" x="208" y="157">
		<key>crm::/dutyModule/logic/QueryDutyItemList.logic</key>
		<name>获得详细列表</name>
		<transaction type="supports"></transaction>
		<parameters>
			<parameter id="1" name="result" classType="java.util.ArrayList" passingType="out">
				<value-key>duty_item_result</value-key>
				<scope>1</scope>
				<description></description>
			</parameter>
			<parameter id="2" name="dutyId" classType="java.lang.String" passingType="in">
				<value-key>dutyid</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="3" name="dItemType" classType="java.lang.String" passingType="in">
				<value-key>ditemtype</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
		</parameters>
		<description></description>
	</logic>
	<connection source="1" target="2" style="1" name=""></connection>
	<connection source="2" target="3" style="1" name=""></connection>
	<connection source="3" target="4" style="1" name=""></connection>
</saturn-action>