<?xml version="1.0" encoding="UTF-8"?>
<saturn-action>
	<information id="0" next="" x="0" y="0">
		<key>/pointModule/action/GetPRListByDec.action</key>
		<name>获得兑换规则</name>
		<description></description>
	</information>
	<transform id="5" next="4" x="418" y="153">
		<value-key>prdec_result</value-key>
		<type>json</type>
		<name>prdec_result</name>
		<contents>
			<content id="1" type="list">
				<content-value-key>prdec_result</content-value-key>
			</content>
		</contents>
		<description></description>
	</transform>
	<logic exception="" id="2" next="5" x="257" y="158">
		<key>crm::/pointModule/logic/GetPRListByDec.logic</key>
		<name>获得兑换规则</name>
		<transaction type="supports"></transaction>
		<parameters>
			<parameter id="1" name="result" classType="java.util.ArrayList" passingType="out">
				<value-key>prdec_result</value-key>
				<scope>1</scope>
				<description>返回SaturnData结果集</description>
			</parameter>
		</parameters>
		<description></description>
	</logic>
	<start id="1" next="2" x="81" y="161">
		<name>开始</name>
		<transaction autorollback="false"></transaction>
		<parameters></parameters>
		<description></description>
	</start>
	<view id="4" next="" x="587" y="183">
		<name>json</name>
		<type>json</type>
		<location>prdec_result</location>
		<description></description>
	</view>
	<connection source="1" target="2" style="1" name=""></connection>
	<connection source="2" target="5" style="1" name=""></connection>
	<connection source="5" target="4" style="1" name=""></connection>
</saturn-action>