<?xml version="1.0" encoding="UTF-8"?>
<saturn-action>
	<information id="0" next="" x="0" y="0">
		<key>/ccioModule/action/GetBindByCard.action</key>
		<name>按卡号获得vin</name>
		<description></description>
	</information>
	<logic exception="" id="2" next="3" x="228" y="152">
		<key>crm::/ccioModule/logic/GetBinding.logic</key>
		<name>获得绑定信息</name>
		<transaction type="supports"></transaction>
		<parameters>
			<parameter id="1" name="result" classType="java.util.ArrayList" passingType="out">
				<value-key>result</value-key>
				<scope>1</scope>
				<description>返回SaturnData结果集</description>
			</parameter>
			<parameter id="2" name="saturnData" classType="edu.ccut.saturn.component.SaturnData" passingType="out">
				<value-key>bindSaturnData</value-key>
				<scope>1</scope>
				<description></description>
			</parameter>
			<parameter id="3" name="b_card" classType="java.lang.String" passingType="in">
				<value-key>b_card</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="4" name="b_vin" classType="java.lang.String" passingType="in">
				<value-key>b_vin</value-key>
				<scope>1</scope>
				<description></description>
			</parameter>
		</parameters>
		<description></description>
	</logic>
	<view id="4" next="" x="468" y="163">
		<name>视图3</name>
		<type>json</type>
		<location>bindSaturnData</location>
		<description></description>
	</view>
	<transform id="3" next="4" x="361" y="153">
		<value-key>bindSaturnData</value-key>
		<type>json</type>
		<name>转移2</name>
		<contents>
			<content id="1" type="saturnData">
				<content-value-key>bindSaturnData</content-value-key>
			</content>
		</contents>
		<description></description>
	</transform>
	<start id="1" next="2" x="81" y="161">
		<name>开始</name>
		<transaction autorollback="false"></transaction>
		<parameters></parameters>
		<description></description>
	</start>
	<connection source="1" target="2" style="1" name=""></connection>
	<connection source="2" target="3" style="1" name=""></connection>
	<connection source="3" target="4" style="1" name=""></connection>
</saturn-action>