<?xml version="1.0" encoding="UTF-8"?>
<saturn-action>
	<information id="0" next="" x="0" y="0">
		<key>/ccioModule/action/GetDictRes.action</key>
		<name>获得基础数据</name>
		<description></description>
	</information>
	<start id="1" next="2" x="81" y="161">
		<name>开始</name>
		<transaction autorollback="false"></transaction>
		<parameters></parameters>
		<description></description>
	</start>
	<view id="4" next="" x="630" y="197">
		<name>视图2</name>
		<type>json</type>
		<location>dictresult</location>
		<description></description>
	</view>
	<logic exception="" id="2" next="3" x="234" y="148">
		<key>crm::/ccioModule/logic/GetDictRes.logic</key>
		<name>获得基础数据</name>
		<transaction type="supports"></transaction>
		<parameters>
			<parameter id="1" name="result" classType="java.util.ArrayList" passingType="out">
				<value-key>dictresult</value-key>
				<scope>1</scope>
				<description>返回SaturnData结果集</description>
			</parameter>
			<parameter id="2" name="d_pid" classType="java.lang.String" passingType="in">
				<value-key>d_pid</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="3" name="d_type" classType="java.lang.String" passingType="in">
				<value-key>d_type</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
		</parameters>
		<description></description>
	</logic>
	<transform id="3" next="4" x="448" y="176">
		<value-key>dictresult</value-key>
		<type>json</type>
		<name>dictjson</name>
		<contents>
			<content id="1" type="list">
				<content-value-key>dictresult</content-value-key>
			</content>
		</contents>
		<description></description>
	</transform>
	<connection source="1" target="2" style="1" name=""></connection>
	<connection source="2" target="3" style="1" name=""></connection>
	<connection source="3" target="4" style="1" name=""></connection>
</saturn-action>