<?xml version="1.0" encoding="UTF-8"?>
<saturn-action>
	<information id="0" next="" x="0" y="0">
		<key>/importModule/action/InsertReserve.action</key>
		<name>导入预约</name>
		<description>导入预约</description>
	</information>
	<connection source="3" target="6" style="1" name=""></connection>
	<connection source="4" target="3" style="1" name=""></connection>
	<view id="11" next="" x="291" y="341">
		<name>error</name>
		<type>jsp</type>
		<location>/crm/importModule/web/error.jsp</location>
		<description></description>
	</view>
	<decision next="" id="8" x="250" y="170">
		<name>选择10</name>
		<if then="11" else="14">
			<expr>filePath==null</expr>
		</if>
		<parameters></parameters>
		<description></description>
	</decision>
	<action id="13" next="" x="680" y="134">
		<key>crm::/importModule/action/QueryImportResult.action</key>
		<name>查询导入结果</name>
		<parameters></parameters>
		<description>查询导入结果</description>
	</action>
	<logic exception="" id="7" next="8" x="148" y="295">
		<key>crm::/importModule/logic/UploadExcel.logic</key>
		<name>UploadExcel</name>
		<transaction type="supports"></transaction>
		<parameters>
			<parameter id="1" name="file" classType="java.lang.Object" passingType="in">
				<value-key>excelFile</value-key>
				<scope>1</scope>
				<description></description>
			</parameter>
			<parameter id="2" name="saveType" classType="java.lang.String" passingType="in">
				<value-key>'reserve'</value-key>
				<scope>1</scope>
				<description></description>
			</parameter>
			<parameter id="3" name="" classType="java.lang.String" passingType="out">
				<value-key>filePath</value-key>
				<scope>1</scope>
				<description></description>
			</parameter>
		</parameters>
		<description></description>
	</logic>
	<start id="1" next="7" x="54" y="149">
		<name>开始</name>
		<transaction autorollback="false"></transaction>
		<parameters></parameters>
		<description></description>
	</start>
	<logic exception="" id="14" next="15" x="379" y="176">
		<key>crm::/importModule/logic/InsertReserveAll.logic</key>
		<name>插入全部预约信息</name>
		<transaction type="supports"></transaction>
		<parameters>
			<parameter id="1" name="importType" classType="java.lang.String" passingType="in">
				<value-key>'reserve'</value-key>
				<scope>1</scope>
				<description></description>
			</parameter>
			<parameter id="2" name="filePath" classType="java.lang.String" passingType="in">
				<value-key>filePath</value-key>
				<scope>1</scope>
				<description></description>
			</parameter>
			<parameter id="3" name="currentTime" classType="java.lang.String" passingType="out">
				<value-key>importdate</value-key>
				<scope>2</scope>
				<description>系统当前时间</description>
			</parameter>
			<parameter id="4" name="fieldValue" classType="java.lang.String" passingType="in">
				<value-key>importtarget</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="5" name="result" classType="java.util.ArrayList" passingType="out">
				<value-key>result</value-key>
				<scope>1</scope>
				<description></description>
			</parameter>
		</parameters>
		<description>插入全部预约信息</description>
	</logic>
	<decision next="" id="15" x="410" y="312">
		<name>选择7</name>
		<if then="12" else="16">
			<expr>result == &quot;success&quot;</expr>
		</if>
		<parameters></parameters>
		<description></description>
	</decision>
	<view id="16" next="" x="573" y="305">
		<name>errornew</name>
		<type>jsp</type>
		<location>/crm/importModule/web/errornew.jsp</location>
		<description></description>
	</view>
	<connection source="9" target="12" style="1" name=""></connection>
	<logic exception="" id="12" next="13" x="527" y="180">
		<key>crm::/importModule/logic/InsertImportData.logic</key>
		<name>插入导入信息记录</name>
		<transaction type="supports"></transaction>
		<parameters>
			<parameter id="1" name="fullkey" classType="java.lang.String" passingType="in">
				<value-key>'http://crm/coreModule/data::crm_reserve'</value-key>
				<scope>1</scope>
				<description>生成SaturnData所需的Fullkey</description>
			</parameter>
			<parameter id="2" name="" classType="java.lang.String" passingType="in">
				<value-key>importdate</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="3" name="fieldValue" classType="java.lang.String" passingType="in">
				<value-key>importtarget</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="4" name="" classType="java.lang.String" passingType="in">
				<value-key>importoper</value-key>
				<scope>1</scope>
				<description></description>
			</parameter>
		</parameters>
		<description>插入导入信息记录</description>
	</logic>
	<connection source="1" target="7" style="1" name=""></connection>
	<connection source="7" target="8" style="1" name=""></connection>
	<connection source="12" target="13" style="1" name=""></connection>
	<connection source="14" target="15" style="1" name=""></connection>
	<connection source="8" target="11" style="1" name="未命名"></connection>
	<connection source="8" target="14" style="2" name="未命名"></connection>
	<connection source="15" target="12" style="1" name="未命名"></connection>
	<connection source="15" target="16" style="2" name="未命名"></connection>
</saturn-action>