<?xml version="1.0" encoding="UTF-8"?>
<saturn-action>
	<information id="0" next="" x="0" y="0">
		<key>/importModule/action/InsertRegulRemind.action</key>
		<name>插入定期保养提醒</name>
		<description>插入定期保养提醒</description>
	</information>
	<start id="1" next="3" x="81" y="161">
		<name>开始</name>
		<transaction autorollback="false"></transaction>
		<parameters></parameters>
		<description></description>
	</start>
	<connection source="2" target="4" style="1" name=""></connection>
	<connection source="8" target="4" style="1" name=""></connection>
	<connection source="4" target="6" style="1" name=""></connection>
	<connection source="6" target="7" style="1" name=""></connection>
	<action id="13" next="" x="664" y="100">
		<key>crm::/importModule/action/QueryImportResult.action</key>
		<name>查询导入结果</name>
		<parameters></parameters>
		<description>查询导入结果</description>
	</action>
	<view id="11" next="" x="213" y="358">
		<name>error</name>
		<type>jsp</type>
		<location>/crm/importModule/web/error.jsp</location>
		<description></description>
	</view>
	<logic exception="" id="3" next="5" x="198" y="150">
		<key>crm::/importModule/logic/UploadExcel.logic</key>
		<name>UploadExcel</name>
		<transaction type="supports"></transaction>
		<parameters>
			<parameter id="1" name="file" classType="java.lang.Object" passingType="in">
				<value-key>excelFile</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="2" name="saveType" classType="java.lang.String" passingType="in">
				<value-key>'regulremind'</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="3" name="" classType="java.lang.String" passingType="out">
				<value-key>filePath</value-key>
				<scope>1</scope>
				<description></description>
			</parameter>
		</parameters>
		<description></description>
	</logic>
	<decision next="" id="5" x="278" y="279">
		<name>选择5</name>
		<if then="11" else="14">
			<expr>filePath==null</expr>
		</if>
		<parameters></parameters>
		<description></description>
	</decision>
	<view id="15" next="" x="530" y="289">
		<name>errornew</name>
		<type>jsp</type>
		<location>/crm/importModule/web/errornew.jsp</location>
		<description></description>
	</view>
	<decision next="" id="16" x="394" y="284">
		<name>选择10</name>
		<if then="12" else="15">
			<expr>result == &quot;success&quot;</expr>
		</if>
		<parameters></parameters>
		<description></description>
	</decision>
	<logic exception="" id="14" next="16" x="335" y="163">
		<key>crm::/importModule/logic/InsertRegulRemindAll.logic</key>
		<name>导入定期保险保养信息</name>
		<transaction type="supports"></transaction>
		<parameters>
			<parameter id="1" name="importType" classType="java.lang.String" passingType="in">
				<value-key>'regulremind'</value-key>
				<scope>1</scope>
				<description></description>
			</parameter>
			<parameter id="2" name="filePath" classType="java.lang.String" passingType="in">
				<value-key>filePath</value-key>
				<scope>1</scope>
				<description></description>
			</parameter>
			<parameter id="3" name="currentTime" classType="java.lang.String" passingType="out">
				<value-key>importdate</value-key>
				<scope>2</scope>
				<description>系统当前时间</description>
			</parameter>
			<parameter id="4" name="fieldValue" classType="java.lang.String" passingType="in">
				<value-key>importtarget</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="5" name="reslut" classType="java.lang.String" passingType="out">
				<value-key>result</value-key>
				<scope>1</scope>
				<description></description>
			</parameter>
		</parameters>
		<description>导入定期保险保养信息</description>
	</logic>
	<connection source="9" target="12" style="1" name=""></connection>
	<logic exception="" id="12" next="13" x="501" y="88">
		<key>crm::/importModule/logic/InsertImportData.logic</key>
		<name>插入导入信息记录</name>
		<transaction type="supports"></transaction>
		<parameters>
			<parameter id="1" name="fullkey" classType="java.lang.String" passingType="in">
				<value-key>'http://crm/coreModule/data::crm_regulremind'</value-key>
				<scope>1</scope>
				<description>生成SaturnData所需的Fullkey</description>
			</parameter>
			<parameter id="2" name="" classType="java.lang.String" passingType="in">
				<value-key>importdate</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="3" name="fieldValue" classType="java.lang.String" passingType="in">
				<value-key>importtarget</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="4" name="" classType="java.lang.String" passingType="in">
				<value-key>importoper</value-key>
				<scope>1</scope>
				<description></description>
			</parameter>
		</parameters>
		<description>插入导入信息记录</description>
	</logic>
	<connection source="1" target="3" style="1" name=""></connection>
	<connection source="12" target="13" style="1" name=""></connection>
	<connection source="3" target="5" style="1" name=""></connection>
	<connection source="14" target="16" style="1" name=""></connection>
	<connection source="16" target="12" style="1" name="未命名"></connection>
	<connection source="16" target="15" style="2" name="未命名"></connection>
	<connection source="5" target="11" style="1" name="未命名"></connection>
	<connection source="5" target="14" style="2" name="未命名"></connection>
</saturn-action>