<?xml version="1.0" encoding="UTF-8"?>
<saturn-action>
	<information id="0" next="" x="0" y="0">
		<key>/reportModule/action/QueryWarranty.action</key>
		<name>查询索赔</name>
		<description></description>
	</information>
	<view id="3" next="" x="452" y="170">
		<name>querywarranty</name>
		<type>jsp</type>
		<location>/crm/reportModule/web/querywarranty.jsp</location>
		<description></description>
	</view>
	<logic exception="" id="2" next="3" x="277" y="161">
		<key>crm::/reportModule/logic/QueryWarranty.logic</key>
		<name>查询索赔</name>
		<transaction type="supports"></transaction>
		<parameters>
			<parameter id="1" name="servintime" classType="java.lang.Object" passingType="in">
				<value-key>servintime</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="2" name="result" classType="java.util.ArrayList" passingType="out">
				<value-key>result</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
		</parameters>
		<description></description>
	</logic>
	<start id="1" next="2" x="81" y="161">
		<name>开始</name>
		<transaction autorollback="false"></transaction>
		<parameters></parameters>
		<description></description>
	</start>
	<connection source="1" target="2" style="1" name=""></connection>
	<connection source="2" target="3" style="1" name=""></connection>
</saturn-action>