<?xml version="1.0" encoding="UTF-8"?>
<saturn-action>
	<information id="0" next="" x="0" y="0">
		<key>/careModule/action/AddCare.action</key>
		<name>添加养护品信息</name>
		<description></description>
	</information>
	<start id="1" next="4" x="81" y="161">
		<name>开始</name>
		<transaction autorollback="false"></transaction>
		<parameters></parameters>
		<description></description>
	</start>
	<data id="4" next="5" x="239" y="173">
		<name>数据2</name>
		<data-scope>2</data-scope>
		<data-prefix>care</data-prefix>
		<data-key>careData</data-key>
		<xmlkey></xmlkey>
		<elementkey></elementkey>
		<data-type classType="edu.ccut.saturn.component.SaturnData" namespace="http://crm/coreModule/data" saturnDataType="crm_care"></data-type>
		<parameters></parameters>
		<description></description>
	</data>
	<connection source="6" target="3" style="1" name=""></connection>
	<action id="3" next="" x="530" y="161">
		<key>crm::/careModule/action/QueryCareList.action</key>
		<name>养护品信息列表</name>
		<parameters></parameters>
		<description></description>
	</action>
	<logic exception="" id="2" next="" x="367" y="129">
		<key>crm::/careModule/logic/AddCare.logic</key>
		<name>添加养护品信息</name>
		<transaction type="supports"></transaction>
		<parameters>
			<parameter id="1" name="saturnData" classType="edu.ccut.saturn.component.SaturnData" passingType="in">
				<value-key>careData</value-key>
				<scope>1</scope>
				<description></description>
			</parameter>
			<parameter id="2" name="" classType="java.lang.String" passingType="in">
				<value-key>${CRM_USER.userid}</value-key>
				<scope>5</scope>
				<description></description>
			</parameter>
			<parameter id="3" name="" classType="java.lang.String" passingType="in">
				<value-key>${CRM_USER.userrealname}</value-key>
				<scope>5</scope>
				<description></description>
			</parameter>
		</parameters>
		<description></description>
	</logic>
	<logic exception="" id="5" next="3" x="337" y="275">
		<key>crm::/careModule/logic/AddCare.logic</key>
		<name>添加养护品信息</name>
		<transaction type="supports"></transaction>
		<parameters>
			<parameter id="1" name="saturnData" classType="edu.ccut.saturn.component.SaturnData" passingType="in">
				<value-key>careData</value-key>
				<scope>1</scope>
				<description></description>
			</parameter>
			<parameter id="2" name="fieldValue" classType="java.lang.String" passingType="in">
				<value-key>${CRM_USER.userid}</value-key>
				<scope>5</scope>
				<description></description>
			</parameter>
			<parameter id="3" name="" classType="java.lang.String" passingType="in">
				<value-key>${CRM_USER.userrealname}</value-key>
				<scope>5</scope>
				<description></description>
			</parameter>
			<parameter id="4" name="bucketnumStr" classType="java.lang.String" passingType="in">
				<value-key>bucketnum</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="5" name="priceStr" classType="java.lang.String" passingType="in">
				<value-key>price</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="6" name="" classType="java.lang.String" passingType="in">
				<value-key>dj</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="7" name="nameStr" classType="java.lang.String" passingType="in">
				<value-key>care_careitems</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
			<parameter id="8" name="" classType="java.lang.String" passingType="in">
				<value-key>sjprice</value-key>
				<scope>2</scope>
				<description></description>
			</parameter>
		</parameters>
		<description></description>
	</logic>
	<connection source="1" target="4" style="1" name=""></connection>
	<connection source="5" target="3" style="1" name=""></connection>
	<connection source="4" target="5" style="1" name=""></connection>
</saturn-action>